const _0xS='5';const START_BALANCE=parseInt(_0xS,10);
const _0xU2R=0.95;function usdToRastr(_0xa){return Math.round(_0xa*_0xU2R*100)/100;}
const NUM_FMT=new Intl.NumberFormat('ru');function formatRastr(_0xa){return NUM_FMT.format(Math.round(_0xa*100)/100)+' ⚙️';}
function getSkinIconUrl(_0xa,_0xb){_0xb=_0xb||128;return 'https://api.yrsproject.ru/public/image/Resize?shortname='+_0xa+'&x='+_0xb+'&y='+_0xb;}
const _0xI={k:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M8 54l6-6 32-32 6 6-32 32-6 6z"/><path d="M44 18l8-8 6 6-8 8z"/></svg>',a:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="28" y="6" width="6" height="52" rx="2"/><path d="M34 8l22 10-22 10z"/></svg>',r:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="4" y="26" width="52" height="6" rx="2"/><rect x="16" y="32" width="8" height="16" rx="1"/><rect x="46" y="20" width="6" height="12" rx="1"/></svg>',p:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="12" y="24" width="40" height="10" rx="2"/><path d="M24 34l6 16h10l-4-16z"/></svg>',ar:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M32 6l20 10v14c0 14-10 22-20 28-10-6-20-14-20-28V16z"/></svg>',h:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M12 34a20 20 0 0140 0v14H12z"/></svg>',m:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="8" y="16" width="48" height="36" rx="4" fill="none" stroke="currentColor" stroke-width="4"/><path d="M28 24v20M18 34h20" stroke="currentColor" stroke-width="4"/></svg>',b:'<svg viewBox="0 0 64 64" fill="currentColor"><circle cx="32" cy="38" r="18"/><path d="M46 22l6-6M44 14l4 4"/></svg>',g:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M32 6l24 18-24 34L8 24z"/></svg>',c:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M8 48h48l4-28-14 12L32 12 18 32 4 20z"/></svg>',t:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M20 8h24v14c0 8-6 12-12 12s-12-4-12-12z"/><rect x="28" y="34" width="8" height="14"/><rect x="20" y="48" width="24" height="8" rx="2"/></svg>',cr:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M8 32h48M32 12v40" stroke="currentColor" stroke-width="4"/></svg>',mk:'<svg viewBox="0 0 64 64" fill="currentColor"><ellipse cx="32" cy="34" rx="20" ry="16"/><circle cx="24" cy="34" r="4" fill="black"/><circle cx="40" cy="34" r="4" fill="black"/></svg>',rk:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M32 4c8 8 12 20 12 32l-12 8-12-8c0-12 4-24 12-32z"/></svg>',tr:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="8" y="28" width="40" height="8" rx="2"/><rect x="20" y="36" width="6" height="16"/></svg>',d:'<svg viewBox="0 0 64 64" fill="currentColor"><circle cx="32" cy="32" r="24" fill="none" stroke="currentColor" stroke-width="3"/><text x="32" y="42" text-anchor="middle" font-size="28" font-weight="bold" fill="currentColor">?</text></svg>'};
const _0xS_C={};Object.keys(_0xI).forEach(function(_0xk){_0xS_C[_0xk]=_0xI[_0xk];});
function renderSkinIcon(_0xs){if(_0xs.shortname){var _0xu=getSkinIconUrl(_0xs.shortname,128);return '<div class="skin-icon"><img src="'+_0xu+'" alt="'+_0xs.name+'" loading="lazy" style="width:100%;height:100%;object-fit:contain" onerror="this.style.display=\'none\';this.parentNode.innerHTML=\''+_0xS_C[_0xs.svg||'d'].replace(/'/g,"\\'")+'\'"></div>';}var _0xk=_0xs.svg||'d';return '<div class="skin-icon">'+(_0xS_C[_0xk]||_0xS_C.d)+'</div>';}
const RARITIES={common:{name:'Обычный',color:'#4aa8ff'},rare:{name:'Редкий',color:'#a55cff'},legendary:{name:'Легендарный',color:'#ff3b3b'},mythical:{name:'МИФИЧЕСКИЙ',color:'#f5c542'}};
const SKINS=[
{id:'horror_bag',name:'Horror Bag',shortname:'sleepingbag',svg:'ar',rarity:'mythical',price:usdToRastr(135.09)},
{id:'big_grin',name:'Big Grin',shortname:'metal.facemask',svg:'mk',rarity:'mythical',price:usdToRastr(133.58)},
{id:'creepy_clown_bandana',name:'Creepy Clown Bandana',shortname:'mask.bandana',svg:'mk',rarity:'mythical',price:usdToRastr(83.07)},
{id:'neon_dragon_garage_door',name:'Neon Dragon Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'mythical',price:usdToRastr(83.51)},
{id:'tempered_mp5',name:'Tempered MP5',shortname:'smg.mp5',svg:'r',rarity:'mythical',price:usdToRastr(533.25)},
{id:'glory_ak47',name:'Glory AK47',shortname:'rifle.ak',svg:'r',rarity:'mythical',price:usdToRastr(296.57)},
{id:'military_camo_mp5',name:'Military Camo MP5',shortname:'smg.mp5',svg:'r',rarity:'mythical',price:usdToRastr(233.32)},
{id:'tempered_mask',name:'Tempered Mask',shortname:'metal.facemask',svg:'mk',rarity:'mythical',price:usdToRastr(197.15)},
{id:'hot_tempered_longsword',name:'Hot-Tempered Longsword',shortname:'knife.combat',svg:'k',rarity:'mythical',price:usdToRastr(196.37)},
{id:'glowing_skull',name:'Glowing Skull',shortname:'metal.facemask',svg:'mk',rarity:'mythical',price:usdToRastr(172.89)},
{id:'christmas_lights',name:'Christmas Lights',shortname:'xmas.lights',svg:'d',rarity:'mythical',price:usdToRastr(160.11)},
{id:'alien_red',name:'Alien Red',shortname:'rifle.ak',svg:'r',rarity:'mythical',price:usdToRastr(156.85)},
{id:'gold_rock',name:'Gold Rock',shortname:'rock',svg:'d',rarity:'mythical',price:usdToRastr(153.44)},
{id:'stainless_facemask',name:'Stainless Facemask',shortname:'metal.facemask',svg:'mk',rarity:'mythical',price:usdToRastr(99.77)},
{id:'legendary_gold_facemask',name:'Legendary Gold Facemask',shortname:'metal.facemask',svg:'mk',rarity:'mythical',price:usdToRastr(91.74)},
{id:'plate_carrier_black',name:'Plate Carrier - Black',shortname:'metal.plate.torso',svg:'ar',rarity:'mythical',price:usdToRastr(88.04)},
{id:'forest_raiders_roadsign_pants',name:'Forest Raiders Roadsign Pants',shortname:'roadsign.kilt',svg:'ar',rarity:'mythical',price:usdToRastr(84.66)},
{id:'after_death_ar',name:'After Death AR',shortname:'rifle.ak',svg:'r',rarity:'mythical',price:usdToRastr(83.54)},
{id:'desert_raiders_facemask',name:'Desert Raiders Facemask',shortname:'metal.facemask',svg:'mk',rarity:'mythical',price:usdToRastr(78.97)},
{id:'tea_vending_machine',name:'Tea Vending Machine',shortname:'vending.machine',svg:'d',rarity:'mythical',price:usdToRastr(71.86)},
{id:'direct_threat_sap',name:'Direct Threat SAP',shortname:'pistol.semiauto',svg:'p',rarity:'legendary',price:usdToRastr(70.79)},
{id:'desert_raiders_chest_plate',name:'Desert Raiders Chest Plate',shortname:'metal.plate.torso',svg:'ar',rarity:'legendary',price:usdToRastr(63.56)},
{id:'forest_raiders_roadsign_vest',name:'Forest Raiders Roadsign Vest',shortname:'roadsign.jacket',svg:'ar',rarity:'legendary',price:usdToRastr(62.08)},
{id:'ak_royale',name:'AK Royale',shortname:'rifle.ak',svg:'r',rarity:'legendary',price:usdToRastr(61.84)},
{id:'space_rocket_work_gloves',name:'Space Rocket Work Gloves',shortname:'gloves',svg:'ar',rarity:'legendary',price:usdToRastr(60.57)},
{id:'shard_of_true_ice',name:'Shard of True Ice',shortname:'gem',svg:'g',rarity:'legendary',price:usdToRastr(59.60)},
{id:'forest_raiders_helmet',name:'Forest Raiders Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'legendary',price:usdToRastr(59.35)},
{id:'ak47_victoria',name:'AK-47 Victoria',shortname:'rifle.ak',svg:'r',rarity:'legendary',price:usdToRastr(54.75)},
{id:'surgeon_scrubs',name:'Surgeon Scrubs',shortname:'hazmatsuit',svg:'ar',rarity:'legendary',price:usdToRastr(52.27)},
{id:'polymer_mp5',name:'Polymer MP5',shortname:'smg.mp5',svg:'r',rarity:'legendary',price:usdToRastr(50.10)},
{id:'forest_raiders_roadsign_gloves',name:'Forest Raiders Roadsign Gloves',shortname:'roadsign.gloves',svg:'ar',rarity:'legendary',price:usdToRastr(42.06)},
{id:'chop_shop_garage_door',name:'Chop Shop Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'legendary',price:usdToRastr(39.01)},
{id:'howling_double_door',name:'Howling Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'legendary',price:usdToRastr(37.58)},
{id:'forest_raiders_pants',name:'Forest Raiders Pants',shortname:'pants',svg:'ar',rarity:'legendary',price:usdToRastr(36.61)},
{id:'whiteout_helmet',name:'Whiteout Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'legendary',price:usdToRastr(35.98)},
{id:'cow_moo_flage_pants',name:'Cow Moo Flage Pants',shortname:'pants',svg:'ar',rarity:'legendary',price:usdToRastr(35.94)},
{id:'double_door_from_hell',name:'Double Door From Hell',shortname:'door.double.hinged.metal',svg:'d',rarity:'legendary',price:usdToRastr(34.99)},
{id:'no_mercy_jacket',name:'No Mercy Jacket',shortname:'jacket',svg:'ar',rarity:'legendary',price:usdToRastr(34.75)},
{id:'desert_raiders_pants',name:'Desert Raiders Pants',shortname:'pants',svg:'ar',rarity:'legendary',price:usdToRastr(33.97)},
{id:'neon_boom_storage',name:'Neon Boom Storage',shortname:'box.wooden.large',svg:'d',rarity:'legendary',price:usdToRastr(32.51)},
{id:'rustige_egg_red',name:'Rustigé Egg - Red',shortname:'egg',svg:'g',rarity:'legendary',price:usdToRastr(31.86)},
{id:'checkpoint_riot_helmet',name:'Checkpoint Riot Helmet',shortname:'riot.helmet',svg:'h',rarity:'legendary',price:usdToRastr(31.53)},
{id:'soviet_carpet',name:'Soviet Carpet',shortname:'rug',svg:'d',rarity:'legendary',price:usdToRastr(30.77)},
{id:'no_mercy_pants',name:'No Mercy Pants',shortname:'pants',svg:'ar',rarity:'legendary',price:usdToRastr(30.77)},
{id:'ak47_from_hell',name:'AK-47 From Hell',shortname:'rifle.ak',svg:'r',rarity:'legendary',price:usdToRastr(29.18)},
{id:'mystic_ak47',name:'Mystic AK47',shortname:'rifle.ak',svg:'r',rarity:'legendary',price:usdToRastr(29.15)},
{id:'desert_raiders_roadsign_vest',name:'Desert Raiders Roadsign Vest',shortname:'roadsign.jacket',svg:'ar',rarity:'legendary',price:usdToRastr(29.01)},
{id:'military_camo_roadsign_kilt',name:'Military Camo Roadsign Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'legendary',price:usdToRastr(28.60)},
{id:'blackout_pants',name:'Blackout Pants',shortname:'pants',svg:'ar',rarity:'legendary',price:usdToRastr(27.41)},
{id:'panda_rug',name:'Panda Rug',shortname:'rug',svg:'d',rarity:'legendary',price:usdToRastr(26.68)},
{id:'desert_raiders_hoodie',name:'Desert Raiders Hoodie',shortname:'hoodie',svg:'ar',rarity:'legendary',price:usdToRastr(26.23)},
{id:'desert_raiders_helmet',name:'Desert Raiders Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'legendary',price:usdToRastr(25.73)},
{id:'press_vest',name:'Press Vest',shortname:'metal.plate.torso',svg:'ar',rarity:'legendary',price:usdToRastr(25.36)},
{id:'dragon_glass_stone_hatchet',name:'Dragon Glass Stone Hatchet',shortname:'hatchet',svg:'a',rarity:'legendary',price:usdToRastr(24.56)},
{id:'blackout_hoodie',name:'Blackout Hoodie',shortname:'hoodie',svg:'ar',rarity:'legendary',price:usdToRastr(24.51)},
{id:'skull_door_knocker',name:'Skull Door Knocker',shortname:'door.hinged.metal',svg:'d',rarity:'legendary',price:usdToRastr(24.02)},
{id:'hot_tempered_revolver',name:'Hot-Tempered Revolver',shortname:'pistol.revolver',svg:'p',rarity:'legendary',price:usdToRastr(23.36)},
{id:'military_kilt',name:'Military Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'legendary',price:usdToRastr(23.09)},
{id:'rat_mask',name:'Rat Mask',shortname:'metal.facemask',svg:'mk',rarity:'legendary',price:usdToRastr(22.97)},
{id:'scorched_hammer',name:'Scorched Hammer',shortname:'hammer',svg:'a',rarity:'legendary',price:usdToRastr(22.63)},
{id:'heat_double_shotgun',name:'Heat Double Shotgun',shortname:'shotgun.double',svg:'r',rarity:'legendary',price:usdToRastr(22.49)},
{id:'wasteland_hunter_gloves',name:'Wasteland Hunter Gloves',shortname:'gloves',svg:'ar',rarity:'legendary',price:usdToRastr(22.06)},
{id:'forest_raiders_facemask',name:'Forest Raiders Facemask',shortname:'metal.facemask',svg:'mk',rarity:'legendary',price:usdToRastr(21.26)},
{id:'blackout_vest',name:'Blackout Vest',shortname:'metal.plate.torso',svg:'ar',rarity:'legendary',price:usdToRastr(21.04)},
{id:'no_mercy_hoodie',name:'No Mercy Hoodie',shortname:'hoodie',svg:'ar',rarity:'legendary',price:usdToRastr(20.74)},
{id:'whiteout_vest',name:'Whiteout Vest',shortname:'metal.plate.torso',svg:'ar',rarity:'legendary',price:usdToRastr(20.04)},
{id:'whiteout_kilt',name:'Whiteout Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'legendary',price:usdToRastr(19.90)},
{id:'polymer_pump_shotgun',name:'Polymer Pump Shotgun',shortname:'shotgun.pump',svg:'r',rarity:'legendary',price:usdToRastr(19.52)},
{id:'desert_raiders_roadsign_pants',name:'Desert Raiders Roadsign Pants',shortname:'roadsign.kilt',svg:'ar',rarity:'legendary',price:usdToRastr(19.44)},
{id:'whiteout_facemask',name:'Whiteout Facemask',shortname:'metal.facemask',svg:'mk',rarity:'legendary',price:usdToRastr(19.33)},
{id:'scientific_fuel_storage',name:'Scientific Fuel Storage',shortname:'box.wooden.large',svg:'d',rarity:'legendary',price:usdToRastr(19.15)},
{id:'playmaker_ak47',name:'Playmaker AK47',shortname:'rifle.ak',svg:'r',rarity:'legendary',price:usdToRastr(18.54)},
{id:'glory_sar',name:'Glory SAR',shortname:'rifle.semiauto',svg:'r',rarity:'legendary',price:usdToRastr(18.49)},
{id:'rox_black_vending_machine',name:'Rox Black Vending Machine',shortname:'vending.machine',svg:'d',rarity:'legendary',price:usdToRastr(18.44)},
{id:'army_bolt_rifle',name:'Army Bolt Rifle',shortname:'rifle.bolt',svg:'r',rarity:'legendary',price:usdToRastr(18.42)},
{id:'comics_ar',name:'Comics AR',shortname:'rifle.ak',svg:'r',rarity:'legendary',price:usdToRastr(18.39)},
{id:'forest_raiders_hoodie',name:'Forest Raiders Hoodie',shortname:'hoodie',svg:'ar',rarity:'legendary',price:usdToRastr(18.25)},
{id:'tribesman_hide_pants',name:'Tribesman Hide Pants',shortname:'attire.hide.pants',svg:'ar',rarity:'rare',price:usdToRastr(18.21)},
{id:'spacesuit',name:'Spacesuit',shortname:'hazmatsuit.spacesuit',svg:'ar',rarity:'rare',price:usdToRastr(18.02)},
{id:'forest_raiders_metal_chest_plate',name:'Forest Raiders Metal Chest Plate',shortname:'metal.plate.torso',svg:'ar',rarity:'rare',price:usdToRastr(17.98)},
{id:'whiteout_hoodie',name:'Whiteout Hoodie',shortname:'hoodie',svg:'ar',rarity:'rare',price:usdToRastr(17.88)},
{id:'comics_sar',name:'Comics SAR',shortname:'rifle.semiauto',svg:'r',rarity:'rare',price:usdToRastr(17.65)},
{id:'cowboy_sheriff_hoodie',name:'Cowboy Sheriff Hoodie',shortname:'hoodie',svg:'ar',rarity:'rare',price:usdToRastr(17.50)},
{id:'brutalist_sheet_metal_door',name:'Brutalist Sheet Metal Door',shortname:'door.hinged.metal',svg:'d',rarity:'rare',price:usdToRastr(17.11)},
{id:'worker_pants',name:'Worker Pants',shortname:'pants',svg:'ar',rarity:'rare',price:usdToRastr(16.60)},
{id:'furious_raider_riot_helmet',name:'Furious Raider Riot Helmet',shortname:'riot.helmet',svg:'h',rarity:'rare',price:usdToRastr(16.28)},
{id:'box_from_hell',name:'Box From Hell',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(15.72)},
{id:'toxic',name:'Toxic',shortname:'rifle.ak',svg:'r',rarity:'rare',price:usdToRastr(15.70)},
{id:'cargo_truck_garage_door',name:'Cargo Truck Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'rare',price:usdToRastr(15.68)},
{id:'scientific_ammo_storage',name:'Scientific Ammo Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(15.53)},
{id:'skeleton_hoodie',name:'Skeleton Hoodie',shortname:'hoodie',svg:'ar',rarity:'rare',price:usdToRastr(15.43)},
{id:'arctic_protection_burlap_headwrap',name:'Arctic Protection Burlap Headwrap',shortname:'burlap.headwrap',svg:'ar',rarity:'rare',price:usdToRastr(15.25)},
{id:'blackout_kilt',name:'Blackout Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'rare',price:usdToRastr(15.18)},
{id:'rustige_egg_ivory',name:'Rustigé Egg - Ivory',shortname:'egg',svg:'g',rarity:'rare',price:usdToRastr(15.14)},
{id:'native_american_hide_shoes',name:'Native American Hide Shoes',shortname:'attire.hide.boots',svg:'ar',rarity:'rare',price:usdToRastr(14.95)},
{id:'imp_sar',name:'IMP SAR',shortname:'rifle.semiauto',svg:'r',rarity:'rare',price:usdToRastr(14.87)},
{id:'blackout_helmet',name:'Blackout Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'rare',price:usdToRastr(14.67)},
{id:'glory_thompson',name:'Glory Thompson',shortname:'smg.thompson',svg:'r',rarity:'rare',price:usdToRastr(14.63)},
{id:'aztek_night_hunter',name:'Aztek Night Hunter',shortname:'metal.facemask',svg:'mk',rarity:'rare',price:usdToRastr(14.55)},
{id:'blackout_gloves',name:'Blackout Gloves',shortname:'gloves',svg:'ar',rarity:'rare',price:usdToRastr(14.27)},
{id:'arctic_protection_burlap_shirt',name:'Arctic Protection Burlap Shirt',shortname:'burlap.shirt',svg:'ar',rarity:'rare',price:usdToRastr(14.19)},
{id:'rabbit_mask',name:'Rabbit Mask',shortname:'metal.facemask',svg:'mk',rarity:'rare',price:usdToRastr(14.08)},
{id:'bombshell_sheet_metal_double_door',name:'Bombshell Sheet Metal Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'rare',price:usdToRastr(13.92)},
{id:'neon_drop_box_storage',name:'Neon Drop Box Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(13.69)},
{id:'cowboy_sheriff_pants',name:'Cowboy Sheriff Pants',shortname:'pants',svg:'ar',rarity:'rare',price:usdToRastr(13.53)},
{id:'spooky_slime_furnace',name:'Spooky Slime Furnace',shortname:'furnace',svg:'d',rarity:'rare',price:usdToRastr(13.49)},
{id:'neon_ore_storage',name:'Neon Ore Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(13.37)},
{id:'desert_patrol_vest',name:'Desert Patrol Vest',shortname:'metal.plate.torso',svg:'ar',rarity:'rare',price:usdToRastr(13.31)},
{id:'no_mercy_facemask',name:'No Mercy Facemask',shortname:'metal.facemask',svg:'mk',rarity:'rare',price:usdToRastr(13.28)},
{id:'military_vest',name:'Military Vest',shortname:'metal.plate.torso',svg:'ar',rarity:'rare',price:usdToRastr(12.89)},
{id:'aztec_long_t_shirt',name:'Aztec Long T-Shirt',shortname:'tshirt.long',svg:'ar',rarity:'rare',price:usdToRastr(12.79)},
{id:'cold_hunter_mp5',name:'Cold Hunter MP5',shortname:'smg.mp5',svg:'r',rarity:'rare',price:usdToRastr(12.76)},
{id:'blackout_boots',name:'Blackout Boots',shortname:'shoes.boots',svg:'ar',rarity:'rare',price:usdToRastr(12.70)},
{id:'uprising_hide_poncho',name:'Uprising Hide Poncho',shortname:'attire.hide.poncho',svg:'ar',rarity:'rare',price:usdToRastr(12.52)},
{id:'neon_scrap_storage',name:'Neon Scrap Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(12.36)},
{id:'reptile_hunter_facemask',name:'Reptile Hunter Facemask',shortname:'metal.facemask',svg:'mk',rarity:'rare',price:usdToRastr(12.31)},
{id:'snow_warrior_hoodie',name:'Snow Warrior Hoodie',shortname:'hoodie',svg:'ar',rarity:'rare',price:usdToRastr(12.26)},
{id:'portable_toilet',name:'Portable Toilet',shortname:'toilet',svg:'d',rarity:'rare',price:usdToRastr(12.22)},
{id:'cobalt_container_double_door',name:'Cobalt Container Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'rare',price:usdToRastr(11.73)},
{id:'high_quality_bag',name:'High Quality Bag',shortname:'sleepingbag',svg:'ar',rarity:'rare',price:usdToRastr(11.66)},
{id:'labyrinth_door',name:'Labyrinth Door',shortname:'door.hinged.metal',svg:'d',rarity:'rare',price:usdToRastr(11.48)},
{id:'silver_leaf_hammer',name:'Silver Leaf Hammer',shortname:'hammer',svg:'a',rarity:'rare',price:usdToRastr(11.47)},
{id:'kiss_ar',name:'Kiss AR',shortname:'rifle.ak',svg:'r',rarity:'rare',price:usdToRastr(11.34)},
{id:'savage_facemask',name:'Savage Facemask',shortname:'metal.facemask',svg:'mk',rarity:'rare',price:usdToRastr(11.16)},
{id:'legacy_bow',name:'Legacy Bow',shortname:'bow.hunting',svg:'cr',rarity:'rare',price:usdToRastr(11.11)},
{id:'training_pants',name:'Training Pants',shortname:'pants',svg:'ar',rarity:'rare',price:usdToRastr(11.10)},
{id:'digger_helmet',name:'Digger Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'rare',price:usdToRastr(11.05)},
{id:'scavenger_facemask',name:'Scavenger Facemask',shortname:'metal.facemask',svg:'mk',rarity:'rare',price:usdToRastr(11.04)},
{id:'fisherman_burlap_pants',name:'Fisherman Burlap Pants',shortname:'burlap.pants',svg:'ar',rarity:'rare',price:usdToRastr(11.02)},
{id:'neon_clothes_storage',name:'Neon Clothes Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(11.01)},
{id:'red_leather_chair',name:'Red Leather Chair',shortname:'chair',svg:'d',rarity:'rare',price:usdToRastr(11.01)},
{id:'elite_forest_camo_hoodie',name:'Elite Forest Camo Hoodie',shortname:'hoodie',svg:'ar',rarity:'rare',price:usdToRastr(10.85)},
{id:'black_acoustic_guitar',name:'Black Acoustic Guitar',shortname:'guitar',svg:'d',rarity:'rare',price:usdToRastr(10.83)},
{id:'cold_hunter_ak',name:'Cold Hunter AK',shortname:'rifle.ak',svg:'r',rarity:'rare',price:usdToRastr(10.83)},
{id:'vandals_peace_door',name:"Vandal's Peace Door",shortname:'door.hinged.metal',svg:'d',rarity:'rare',price:usdToRastr(10.74)},
{id:'neon_sign_pack',name:'Neon Sign Pack',shortname:'sign.pack',svg:'d',rarity:'rare',price:usdToRastr(10.67)},
{id:'scientific_electrical_storage',name:'Scientific Electrical Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(10.62)},
{id:'tempered_ak47',name:'Tempered AK47',shortname:'rifle.ak',svg:'r',rarity:'rare',price:usdToRastr(10.55)},
{id:'protector_sheet_metal_double_door',name:'Protector Sheet Metal Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'rare',price:usdToRastr(10.50)},
{id:'comics_hoodie',name:'Comics Hoodie',shortname:'hoodie',svg:'ar',rarity:'rare',price:usdToRastr(10.50)},
{id:'neon_elec_storage',name:'Neon Elec Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(10.38)},
{id:'addicted_guitarist',name:'Addicted Guitarist',shortname:'guitar',svg:'d',rarity:'rare',price:usdToRastr(10.33)},
{id:'heat_seeker_thompson',name:'Heat Seeker Thompson',shortname:'smg.thompson',svg:'r',rarity:'rare',price:usdToRastr(10.22)},
{id:'christmas_locker',name:'Christmas Locker',shortname:'locker',svg:'d',rarity:'rare',price:usdToRastr(10.16)},
{id:'military_roadsign_gloves',name:'Military Roadsign Gloves',shortname:'roadsign.gloves',svg:'ar',rarity:'rare',price:usdToRastr(10.06)},
{id:'knight_templar_kilt',name:'Knight Templar Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'rare',price:usdToRastr(9.96)},
{id:'neon_wood_storage',name:'Neon Wood Storage',shortname:'box.wooden.large',svg:'d',rarity:'rare',price:usdToRastr(9.94)},
{id:'dark_silver_python',name:'Dark Silver Python',shortname:'pistol.python',svg:'p',rarity:'rare',price:usdToRastr(9.89)},
{id:'grey_wolf_hide_poncho',name:'Grey Wolf Hide Poncho',shortname:'attire.hide.poncho',svg:'ar',rarity:'rare',price:usdToRastr(9.88)},
{id:'greening_area_double_door',name:'Greening Area Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'rare',price:usdToRastr(9.87)},
{id:'predator_pants',name:'Predator Pants',shortname:'pants',svg:'ar',rarity:'rare',price:usdToRastr(9.86)},
{id:'stinger_icepick',name:'Stinger Icepick',shortname:'icepick',svg:'a',rarity:'rare',price:usdToRastr(9.82)},
{id:'farmer_overalls_bottom',name:'Farmer Overalls Bottom',shortname:'pants',svg:'ar',rarity:'rare',price:usdToRastr(9.82)},
{id:'blackout_bow',name:'Blackout Bow',shortname:'bow.hunting',svg:'cr',rarity:'rare',price:usdToRastr(9.82)},
{id:'no_mercy_gloves',name:'No Mercy Gloves',shortname:'gloves',svg:'ar',rarity:'rare',price:usdToRastr(9.79)},
{id:'cobalt_personal_locker',name:'Cobalt Personal Locker',shortname:'locker',svg:'d',rarity:'rare',price:usdToRastr(9.79)},
{id:'desert_patrol_helmet',name:'Desert Patrol Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'rare',price:usdToRastr(9.78)},
{id:'training_hoodie',name:'Training Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(9.77)},
{id:'cargo_heli_storage',name:'Cargo Heli Storage',shortname:'box.wooden.large',svg:'d',rarity:'common',price:usdToRastr(9.72)},
{id:'army_facemask',name:'Army Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(9.63)},
{id:'tools_supply_container',name:'Tools Supply Container',shortname:'box.wooden.large',svg:'d',rarity:'common',price:usdToRastr(9.51)},
{id:'burglar_mask',name:'Burglar Mask',shortname:'mask.bandana',svg:'mk',rarity:'common',price:usdToRastr(9.47)},
{id:'tribesman_hide_shirt',name:'Tribesman Hide Shirt',shortname:'attire.hide.helterneck',svg:'ar',rarity:'common',price:usdToRastr(9.47)},
{id:'blackout_jacket',name:'Blackout Jacket',shortname:'jacket',svg:'ar',rarity:'common',price:usdToRastr(9.40)},
{id:'jpeg_roadsign_gloves',name:'JPEG Roadsign Gloves',shortname:'roadsign.gloves',svg:'ar',rarity:'common',price:usdToRastr(9.36)},
{id:'bombshell_m249',name:'Bombshell M249',shortname:'lmg.m249',svg:'r',rarity:'common',price:usdToRastr(9.32)},
{id:'military_helmet',name:'Military Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(9.30)},
{id:'army_armored_helmet',name:'Army Armored Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(9.23)},
{id:'desert_patrol_pants',name:'Desert Patrol Pants',shortname:'pants',svg:'ar',rarity:'common',price:usdToRastr(9.22)},
{id:'beauty_industry_double_door',name:'Beauty Industry Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(9.21)},
{id:'brutalist_garage_door',name:'Brutalist Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'common',price:usdToRastr(9.18)},
{id:'burlap_bandit_shirt',name:'Burlap Bandit Shirt',shortname:'burlap.shirt',svg:'ar',rarity:'common',price:usdToRastr(9.13)},
{id:'popstar',name:'Popstar',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(9.12)},
{id:'thundergold_helmet',name:'Thundergold Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(9.00)},
{id:'neon_bismuth_metal_double_door',name:'Neon Bismuth Metal Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(8.97)},
{id:'abyss_metal_double_door',name:'Abyss Metal Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(8.93)},
{id:'operator_helmet',name:'Operator Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(8.92)},
{id:'scientific_guns_storage',name:'Scientific Guns Storage',shortname:'box.wooden.large',svg:'d',rarity:'common',price:usdToRastr(8.88)},
{id:'redemption_kilt',name:'Redemption Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(8.88)},
{id:'whiteout_pants',name:'Whiteout Pants',shortname:'pants',svg:'ar',rarity:'common',price:usdToRastr(8.88)},
{id:'knights_templar_facemask',name:'Knights Templar Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(8.81)},
{id:'blue_tarp_skirt',name:'Blue Tarp Skirt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(8.71)},
{id:'forest_raiders_boots',name:'Forest Raiders Boots',shortname:'shoes.boots',svg:'ar',rarity:'common',price:usdToRastr(8.69)},
{id:'kayak_helmet',name:'Kayak Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(8.66)},
{id:'boxers_bandages',name:"Boxer's Bandages",shortname:'gloves',svg:'ar',rarity:'common',price:usdToRastr(8.62)},
{id:'urban_night_door',name:'Urban Night Door',shortname:'door.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(8.60)},
{id:'reptile_hunter_chestplate',name:'Reptile Hunter Chestplate',shortname:'metal.plate.torso',svg:'ar',rarity:'common',price:usdToRastr(8.59)},
{id:'crypt_armored_double_door',name:'Crypt Armored Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(8.59)},
{id:'popstar_garage_door',name:'Popstar Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'common',price:usdToRastr(8.57)},
{id:'arctic_protection_burlap_pants',name:'Arctic Protection Burlap Pants',shortname:'burlap.pants',svg:'ar',rarity:'common',price:usdToRastr(8.46)},
{id:'thundergold_roadsign_kilt',name:'Thundergold Roadsign Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(8.41)},
{id:'polymer_bar',name:'Polymer Bar',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(8.34)},
{id:'training_kilt',name:'Training Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(8.32)},
{id:'phantom_hoodie',name:'Phantom Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(8.31)},
{id:'whiteout_roadsign_gloves',name:'Whiteout Roadsign Gloves',shortname:'roadsign.gloves',svg:'ar',rarity:'common',price:usdToRastr(8.29)},
{id:'weapon_barrel',name:'Weapon Barrel',shortname:'box.wooden.large',svg:'d',rarity:'common',price:usdToRastr(8.17)},
{id:'cargo_heli_locker',name:'Cargo Heli Locker',shortname:'locker',svg:'d',rarity:'common',price:usdToRastr(8.10)},
{id:'jack_sheet_metal_double_door',name:'Jack Sheet Metal Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(8.04)},
{id:'uprising_hide_shoes',name:'Uprising Hide Shoes',shortname:'attire.hide.boots',svg:'ar',rarity:'common',price:usdToRastr(8.04)},
{id:'comics_jackhammer',name:'Comics Jackhammer',shortname:'jackhammer',svg:'a',rarity:'common',price:usdToRastr(8.04)},
{id:'forest_camouflage_net',name:'Forest Camouflage Net',shortname:'net',svg:'d',rarity:'common',price:usdToRastr(8.01)},
{id:'hellcore_thompson',name:'Hellcore Thompson',shortname:'smg.thompson',svg:'r',rarity:'common',price:usdToRastr(8.00)},
{id:'forest_camo_bag',name:'Forest Camo Bag',shortname:'sleepingbag',svg:'ar',rarity:'common',price:usdToRastr(7.96)},
{id:'cobalt_coffee',name:'Cobalt Coffee',shortname:'coffeecan.helmet',svg:'d',rarity:'common',price:usdToRastr(7.95)},
{id:'knights_templar_hoodie',name:'Knights Templar Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(7.92)},
{id:'batteries_not_included',name:'Batteries Not Included',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(7.90)},
{id:'fisherman_burlap_shirt',name:'Fisherman Burlap Shirt',shortname:'burlap.shirt',svg:'ar',rarity:'common',price:usdToRastr(7.87)},
{id:'volcanic_stone_hatchet',name:'Volcanic Stone Hatchet',shortname:'hatchet',svg:'a',rarity:'common',price:usdToRastr(7.87)},
{id:'space_station_armored_double_door',name:'Space Station Armored Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(7.87)},
{id:'going_deep_garage_door',name:'Going Deep Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'common',price:usdToRastr(7.87)},
{id:'sleazy_rider',name:'Sleazy Rider',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(7.86)},
{id:'cardboard_kilt',name:'Cardboard Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(7.86)},
{id:'grass_rug',name:'Grass Rug',shortname:'rug',svg:'d',rarity:'common',price:usdToRastr(7.84)},
{id:'survivor_lr300',name:'Survivor LR-300',shortname:'rifle.lr300',svg:'r',rarity:'common',price:usdToRastr(7.75)},
{id:'glory_mask',name:'Glory Mask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(7.71)},
{id:'cow_moo_flage_gloves',name:'Cow Moo Flage Gloves',shortname:'gloves',svg:'ar',rarity:'common',price:usdToRastr(7.68)},
{id:'whiteout_chestplate',name:'Whiteout Chestplate',shortname:'metal.plate.torso',svg:'ar',rarity:'common',price:usdToRastr(7.67)},
{id:'blackout_python',name:'Blackout Python',shortname:'pistol.python',svg:'p',rarity:'common',price:usdToRastr(7.66)},
{id:'sakura_ar',name:'Sakura AR',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(7.65)},
{id:'urban_ice_hoodie',name:'Urban Ice Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(7.62)},
{id:'no_mercy_ak47',name:'No Mercy AK47',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(7.58)},
{id:'salvaged_plating_armor',name:'Salvaged Plating Armor',shortname:'metal.plate.torso',svg:'ar',rarity:'common',price:usdToRastr(7.56)},
{id:'predator_hoodie',name:'Predator Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(7.54)},
{id:'big_burger',name:'Big Burger',shortname:'food.burger',svg:'m',rarity:'common',price:usdToRastr(7.54)},
{id:'urban_vending_machine',name:'Urban Vending Machine',shortname:'vending.machine',svg:'d',rarity:'common',price:usdToRastr(7.53)},
{id:'faded_sap',name:'Faded SAP',shortname:'pistol.semiauto',svg:'p',rarity:'common',price:usdToRastr(7.51)},
{id:'cowboy_sheriff_hat',name:'Cowboy Sheriff Hat',shortname:'hat',svg:'ar',rarity:'common',price:usdToRastr(7.51)},
{id:'desert_conqueror_hoodie',name:'Desert Conqueror Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(7.51)},
{id:'military_facemask',name:'Military Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(7.51)},
{id:'scientific_gunpowder_storage',name:'Scientific Gunpowder Storage',shortname:'box.wooden.large',svg:'d',rarity:'common',price:usdToRastr(7.49)},
{id:'danger_fork',name:'Danger Fork',shortname:'fork',svg:'k',rarity:'common',price:usdToRastr(7.42)},
{id:'bee_cosplay_facemask',name:'Bee Cosplay Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(7.39)},
{id:'farmer_straw_hat',name:'Farmer Straw Hat',shortname:'hat',svg:'ar',rarity:'common',price:usdToRastr(7.34)},
{id:'homemade_shorts',name:'Homemade Shorts',shortname:'pants.shorts',svg:'ar',rarity:'common',price:usdToRastr(7.33)},
{id:'ancient_gods_furnace',name:'Ancient Gods Furnace',shortname:'furnace',svg:'d',rarity:'common',price:usdToRastr(7.32)},
{id:'fireflies_metal_door',name:'Fireflies Metal Door',shortname:'door.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(7.30)},
{id:'fish_shoes',name:'Fish Shoes',shortname:'shoes.boots',svg:'ar',rarity:'common',price:usdToRastr(7.30)},
{id:'black_gold_kilt',name:'Black Gold Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(7.29)},
{id:'blackout_facemask',name:'Blackout Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(7.25)},
{id:'uprising_stone_pickaxe',name:'Uprising Stone Pickaxe',shortname:'pickaxe',svg:'a',rarity:'common',price:usdToRastr(7.21)},
{id:'neon_bismuth_armored_double_door',name:'Neon Bismuth Armored Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(7.19)},
{id:'training_gloves',name:'Training Gloves',shortname:'gloves',svg:'ar',rarity:'common',price:usdToRastr(7.14)},
{id:'reptile_hunter_vest',name:'Reptile Hunter Vest',shortname:'metal.plate.torso',svg:'ar',rarity:'common',price:usdToRastr(7.12)},
{id:'bee_cosplay_chestplate',name:'Bee Cosplay Chestplate',shortname:'metal.plate.torso',svg:'ar',rarity:'common',price:usdToRastr(7.11)},
{id:'pirate_sheet_metal_door',name:'Pirate Sheet Metal Door',shortname:'door.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(7.09)},
{id:'rusty_bucket_helmet',name:'Rusty Bucket Helmet',shortname:'bucket.helmet',svg:'h',rarity:'common',price:usdToRastr(7.07)},
{id:'blackout_ar',name:'Blackout AR',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(7.05)},
{id:'easter_chick_hammer',name:'Easter Chick Hammer',shortname:'hammer',svg:'a',rarity:'common',price:usdToRastr(7.00)},
{id:'heat_seeker_revolver',name:'Heat Seeker Revolver',shortname:'pistol.revolver',svg:'p',rarity:'common',price:usdToRastr(6.99)},
{id:'mummy_wraps',name:'Mummy Wraps',shortname:'burlap.gloves',svg:'ar',rarity:'common',price:usdToRastr(6.97)},
{id:'bombshell_sheet_metal_door',name:'Bombshell Sheet Metal Door',shortname:'door.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(6.97)},
{id:'no_mercy_helmet',name:'No Mercy Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(6.96)},
{id:'flower_hat',name:'Flower Hat',shortname:'hat',svg:'ar',rarity:'common',price:usdToRastr(6.95)},
{id:'yellow_police_jacket',name:'Yellow Police Jacket',shortname:'jacket',svg:'ar',rarity:'common',price:usdToRastr(6.91)},
{id:'bombshell_garage_door',name:'Bombshell Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'common',price:usdToRastr(6.91)},
{id:'glory_gloves',name:'Glory Gloves',shortname:'gloves',svg:'ar',rarity:'common',price:usdToRastr(6.90)},
{id:'cardboard_helmet',name:'Cardboard Helmet',shortname:'bucket.helmet',svg:'h',rarity:'common',price:usdToRastr(6.90)},
{id:'lavapick',name:'Lavapick',shortname:'pickaxe',svg:'a',rarity:'common',price:usdToRastr(6.88)},
{id:'porcelain_ar',name:'Porcelain AR',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(6.87)},
{id:'spooky_speaker',name:'Spooky Speaker',shortname:'speaker',svg:'d',rarity:'common',price:usdToRastr(6.86)},
{id:'polished_obsidian_furnace',name:'Polished Obsidian Furnace',shortname:'furnace',svg:'d',rarity:'common',price:usdToRastr(6.78)},
{id:'blackout_mp5',name:'Blackout MP5',shortname:'smg.mp5',svg:'r',rarity:'common',price:usdToRastr(6.74)},
{id:'carbon_facemask',name:'Carbon Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(6.73)},
{id:'pirate_bed',name:'Pirate Bed',shortname:'bed',svg:'d',rarity:'common',price:usdToRastr(6.72)},
{id:'uap_pilot_sleeping_bag',name:'UAP Pilot Sleeping Bag',shortname:'sleepingbag',svg:'d',rarity:'common',price:usdToRastr(6.72)},
{id:'no_mercy_garage_door',name:'No Mercy Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'common',price:usdToRastr(6.69)},
{id:'tactical_leather_gloves',name:'Tactical Leather Gloves',shortname:'gloves',svg:'ar',rarity:'common',price:usdToRastr(6.69)},
{id:'metalhead_m39',name:'Metalhead M39',shortname:'rifle.m39',svg:'r',rarity:'common',price:usdToRastr(6.68)},
{id:'neon_frags_storage',name:'Neon Frags Storage',shortname:'box.wooden.large',svg:'d',rarity:'common',price:usdToRastr(6.65)},
{id:'no_mercy_kilt',name:'No Mercy Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(6.63)},
{id:'no_mercy_mp5',name:'No Mercy MP5',shortname:'smg.mp5',svg:'r',rarity:'common',price:usdToRastr(6.58)},
{id:'aztec_jade_hachet',name:'Aztec Jade Hachet',shortname:'hatchet',svg:'a',rarity:'common',price:usdToRastr(6.57)},
{id:'urban_light_sar',name:'Urban Light SAR',shortname:'rifle.semiauto',svg:'r',rarity:'common',price:usdToRastr(6.57)},
{id:'abyss_sleeping_bag',name:'Abyss Sleeping Bag',shortname:'sleepingbag',svg:'d',rarity:'common',price:usdToRastr(6.55)},
{id:'comics_sleeping_bag',name:'Comics Sleeping Bag',shortname:'sleepingbag',svg:'d',rarity:'common',price:usdToRastr(6.53)},
{id:'neon_charcoal_storage',name:'Neon Charcoal Storage',shortname:'box.wooden.large',svg:'d',rarity:'common',price:usdToRastr(6.49)},
{id:'wasteland_hunter_hoodie',name:'Wasteland Hunter Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(6.46)},
{id:'elite_forest_camo_pants',name:'Elite Forest Camo Pants',shortname:'pants',svg:'ar',rarity:'common',price:usdToRastr(6.45)},
{id:'thundergold_facemask',name:'Thundergold Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(6.39)},
{id:'desert_conqueror_pants',name:'Desert Conqueror Pants',shortname:'pants',svg:'ar',rarity:'common',price:usdToRastr(6.39)},
{id:'cobalt_container_metal_door',name:'Cobalt Container Metal Door',shortname:'door.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(6.38)},
{id:'sand_rhino_facemask',name:'Sand Rhino Facemask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(6.38)},
{id:'military_chestplate',name:'Military Chestplate',shortname:'metal.plate.torso',svg:'ar',rarity:'common',price:usdToRastr(6.36)},
{id:'abyss_boots',name:'Abyss Boots',shortname:'shoes.boots',svg:'ar',rarity:'common',price:usdToRastr(6.35)},
{id:'neon_pumpkin_metal_double_door',name:'Neon Pumpkin Metal Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(6.34)},
{id:'tea_ceremony_knife',name:'Tea Ceremony Knife',shortname:'knife.bone',svg:'k',rarity:'common',price:usdToRastr(6.30)},
{id:'reptile_hunter_large_backpack',name:'Reptile Hunter Large Backpack',shortname:'backpack',svg:'ar',rarity:'common',price:usdToRastr(6.29)},
{id:'black_diamond_pants',name:'Black Diamond Pants',shortname:'pants',svg:'ar',rarity:'common',price:usdToRastr(6.29)},
{id:'greening_area_garage_door',name:'Greening Area Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'common',price:usdToRastr(6.27)},
{id:'furnace_from_hell',name:'Furnace From Hell',shortname:'furnace',svg:'d',rarity:'common',price:usdToRastr(6.25)},
{id:'rainbow_pony_ar',name:'Rainbow Pony AR',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(6.25)},
{id:'anubis_ak47',name:'Anubis AK47',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(6.24)},
{id:'battle_scarred_aks47',name:'Battle-Scarred AKS47',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(6.21)},
{id:'dragon_rage_hoodie',name:'Dragon Rage Hoodie',shortname:'hoodie',svg:'ar',rarity:'common',price:usdToRastr(6.18)},
{id:'heavenly_legion_kilt',name:'Heavenly Legion Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(6.16)},
{id:'knights_templar_chestplate',name:'Knights Templar Chestplate',shortname:'metal.plate.torso',svg:'ar',rarity:'common',price:usdToRastr(6.16)},
{id:'wasteland_hunter_pants',name:'Wasteland Hunter Pants',shortname:'pants',svg:'ar',rarity:'common',price:usdToRastr(6.15)},
{id:'hazard_semi_auto_rifle',name:'Hazard Semi Auto Rifle',shortname:'rifle.semiauto',svg:'r',rarity:'common',price:usdToRastr(6.15)},
{id:'flashbacks_helmet',name:'Flashbacks Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(6.13)},
{id:'nordic_beast_kilt',name:'Nordic Beast Kilt',shortname:'roadsign.kilt',svg:'ar',rarity:'common',price:usdToRastr(6.13)},
{id:'wasteland_hunter_boots',name:'Wasteland Hunter Boots',shortname:'shoes.boots',svg:'ar',rarity:'common',price:usdToRastr(6.10)},
{id:'cyber_core_mp5',name:'Cyber Core MP5',shortname:'smg.mp5',svg:'r',rarity:'common',price:usdToRastr(6.08)},
{id:'bandit_rug',name:'Bandit Rug',shortname:'rug',svg:'d',rarity:'common',price:usdToRastr(6.07)},
{id:'ancient_totem_furnace',name:'Ancient Totem Furnace',shortname:'furnace',svg:'d',rarity:'common',price:usdToRastr(6.07)},
{id:'black_gold_m249',name:'Black Gold M249',shortname:'lmg.m249',svg:'r',rarity:'common',price:usdToRastr(6.02)},
{id:'phantom_lr300',name:'Phantom LR-300',shortname:'rifle.lr300',svg:'r',rarity:'common',price:usdToRastr(5.98)},
{id:'road_romeo_helmet',name:'Road Romeo Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(5.98)},
{id:'rust_goalkeeper_shorts',name:'Rust Goalkeeper Shorts',shortname:'pants.shorts',svg:'ar',rarity:'common',price:usdToRastr(5.97)},
{id:'azul_ak47',name:'Azul AK47',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(5.97)},
{id:'flashbacks_pants',name:'Flashbacks Pants',shortname:'pants',svg:'ar',rarity:'common',price:usdToRastr(5.93)},
{id:'twisted_metal_double_door',name:'Twisted Metal Double Door',shortname:'door.double.hinged.metal',svg:'d',rarity:'common',price:usdToRastr(5.92)},
{id:'dungeon_garage_door',name:'Dungeon Garage Door',shortname:'wall.frame.garagedoor',svg:'d',rarity:'common',price:usdToRastr(5.91)},
{id:'skull_bandana',name:'Skull Bandana',shortname:'mask.bandana',svg:'mk',rarity:'common',price:usdToRastr(5.89)},
{id:'black_diamond_gloves',name:'Black Diamond Gloves',shortname:'gloves',svg:'ar',rarity:'common',price:usdToRastr(5.85)},
{id:'glorious_ak',name:'Glorious AK',shortname:'rifle.ak',svg:'r',rarity:'common',price:usdToRastr(5.82)},
{id:'tiger_mask',name:'Tiger Mask',shortname:'metal.facemask',svg:'mk',rarity:'common',price:usdToRastr(5.82)},
{id:'full_metal_helmet',name:'Full Metal Helmet',shortname:'coffeecan.helmet',svg:'h',rarity:'common',price:usdToRastr(5.80)},
{id:'rock',name:'Камень',shortname:'rock',svg:'d',rarity:'common',price:usdToRastr(0.10)},
{id:'torch',name:'Факел',shortname:'torch',svg:'d',rarity:'common',price:usdToRastr(0.15)},
{id:'bandage',name:'Бинты',shortname:'bandage',svg:'m',rarity:'common',price:usdToRastr(0.20)},
{id:'revolver_basic',name:'Револьвер',shortname:'pistol.revolver',svg:'p',rarity:'common',price:usdToRastr(0.50)},
{id:'wooden_spear',name:'Деревянное копьё',shortname:'spear.wooden',svg:'r',rarity:'common',price:usdToRastr(0.80)},
{id:'stone_hatchet_basic',name:'Каменный топор',shortname:'stonehatchet',svg:'a',rarity:'common',price:usdToRastr(1.00)},
{id:'bow_basic',name:'Лук',shortname:'bow.hunting',svg:'cr',rarity:'common',price:usdToRastr(1.50)},
{id:'crossbow_basic',name:'Арбалет',shortname:'crossbow',svg:'cr',rarity:'common',price:usdToRastr(2.00)},
{id:'bone_knife',name:'Костяной нож',shortname:'knife.bone',svg:'k',rarity:'common',price:usdToRastr(2.50)},
{id:'stone_spear',name:'Каменное копьё',shortname:'spear.stone',svg:'r',rarity:'common',price:usdToRastr(3.00)},
{id:'eoka_pistol',name:'Eoka Pistol',shortname:'pistol.eoka',svg:'p',rarity:'common',price:usdToRastr(3.50)},
{id:'waterpipe_shotgun',name:'Водопроводный дробовик',shortname:'shotgun.waterpipe',svg:'r',rarity:'common',price:usdToRastr(4.00)},
{id:'semi_auto_pistol',name:'Semi-Auto Pistol',shortname:'pistol.semiauto',svg:'p',rarity:'common',price:usdToRastr(4.50)},
{id:'compound_bow',name:'Составной лук',shortname:'bow.compound',svg:'cr',rarity:'common',price:usdToRastr(5.00)}
];
var SKIN_BY_ID={};SKINS.forEach(function(s){SKIN_BY_ID[s.id]=s;});
function resolveSkin(item){if(!item)return null;return SKIN_BY_ID[item.id]||item;}
