/* RASTRGRADE SKINS v35 — с skinId для реальных картинок */

const START_BALANCE = 50000000000;
const USD_TO_RASTR = 0.95;
function usdToRastr(usd) { return Math.round(usd * USD_TO_RASTR * 100) / 100; }

const NUM_FMT = new Intl.NumberFormat('ru');
function formatRastr(v) { return NUM_FMT.format(Math.round(v * 100) / 100) + ' ⚙️'; }

/* API Hougan — РЕАЛЬНЫЕ ИКОНКИ СКИНОВ по skinId */
function getSkinIconUrl(skin, size) {
    size = size || 128;
    // Если есть skinId — используем API Hougan (реальная иконка скина)
    if (skin.skinId) {
        return 'http://api.hougan.space/rust/skin/getImage/' + skin.skinId;
    }
    // Fallback — SVG
    return null;
}

/* SVG fallback */
const ICON_SVG = {
    knife:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M8 54l6-6 32-32 6 6-32 32-6 6z"/><path d="M44 18l8-8 6 6-8 8z"/></svg>',
    axe:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="28" y="6" width="6" height="52" rx="2"/><path d="M34 8l22 10-22 10z"/></svg>',
    rifle:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="4" y="26" width="52" height="6" rx="2"/><rect x="16" y="32" width="8" height="16" rx="1"/><rect x="46" y="20" width="6" height="12" rx="1"/></svg>',
    pistol:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="12" y="24" width="40" height="10" rx="2"/><path d="M24 34l6 16h10l-4-16z"/></svg>',
    armor:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M32 6l20 10v14c0 14-10 22-20 28-10-6-20-14-20-28V16z"/></svg>',
    helmet:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M12 34a20 20 0 0140 0v14H12z"/></svg>',
    medkit:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="8" y="16" width="48" height="36" rx="4" fill="none" stroke="currentColor" stroke-width="4"/><path d="M28 24v20M18 34h20" stroke="currentColor" stroke-width="4"/></svg>',
    bomb:'<svg viewBox="0 0 64 64" fill="currentColor"><circle cx="32" cy="38" r="18"/><path d="M46 22l6-6M44 14l4 4"/></svg>',
    gem:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M32 6l24 18-24 34L8 24z"/></svg>',
    crown:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M8 48h48l4-28-14 12L32 12 18 32 4 20z"/></svg>',
    trophy:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M20 8h24v14c0 8-6 12-12 12s-12-4-12-12z"/><rect x="28" y="34" width="8" height="14"/><rect x="20" y="48" width="24" height="8" rx="2"/></svg>',
    crossbow:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M8 32h48M32 12v40" stroke="currentColor" stroke-width="4"/></svg>',
    mask:'<svg viewBox="0 0 64 64" fill="currentColor"><ellipse cx="32" cy="34" rx="20" ry="16"/><circle cx="24" cy="34" r="4" fill="black"/><circle cx="40" cy="34" r="4" fill="black"/></svg>',
    rocket:'<svg viewBox="0 0 64 64" fill="currentColor"><path d="M32 4c8 8 12 20 12 32l-12 8-12-8c0-12 4-24 12-32z"/></svg>',
    turret:'<svg viewBox="0 0 64 64" fill="currentColor"><rect x="8" y="28" width="40" height="8" rx="2"/><rect x="20" y="36" width="6" height="16"/></svg>',
    default:'<svg viewBox="0 0 64 64" fill="currentColor"><circle cx="32" cy="32" r="24" fill="none" stroke="currentColor" stroke-width="3"/><text x="32" y="42" text-anchor="middle" font-size="28" font-weight="bold" fill="currentColor">?</text></svg>'
};
const SVG_CACHE = {}; Object.keys(ICON_SVG).forEach(function(k){ SVG_CACHE[k] = ICON_SVG[k]; });

function renderSkinIcon(skin) {
    var url = getSkinIconUrl(skin);
    if (url) {
        return '<div class="skin-icon"><img src="' + url + '" alt="' + skin.name + '" style="width:100%;height:100%;object-fit:contain" onerror="this.style.display=\'none\';this.parentNode.innerHTML=\'' + SVG_CACHE[skin.svg || 'default'].replace(/'/g, "\\'") + '\'"></div>';
    }
    var svgKey = skin.svg || 'default';
    return '<div class="skin-icon">' + (SVG_CACHE[svgKey] || SVG_CACHE.default) + '</div>';
}

const RARITIES = {
    common:    { name:'Обычный',     color:'#4aa8ff' },
    rare:      { name:'Редкий',      color:'#a55cff' },
    legendary: { name:'Легендарный', color:'#ff3b3b' },
    mythical:  { name:'МИФИЧЕСКИЙ',  color:'#f5c542' }
};

/* ============================================================
   SKINS — 200+ скинов с skinId где найдено
   Формат: {id, name, svg, rarity, price, skinId?}
   ============================================================ */
const SKINS = [
    // 🟡 ЗОЛОТІ (mythical) — с skinId
    {id:'horror_bag', name:'Horror Bag', svg:'armor', rarity:'mythical', price:usdToRastr(135.09), skinId:535099192},
    {id:'big_grin', name:'Big Grin', svg:'mask', rarity:'mythical', price:usdToRastr(133.58), skinId:784316334},
    {id:'creepy_clown_bandana', name:'Creepy Clown Bandana', svg:'mask', rarity:'mythical', price:usdToRastr(83.07)},
    {id:'neon_dragon_garage_door', name:'Neon Dragon Garage Door', svg:'default', rarity:'mythical', price:usdToRastr(83.51), skinId:3149841519},
    {id:'tempered_mp5', name:'Tempered MP5', svg:'rifle', rarity:'mythical', price:usdToRastr(533.25), skinId:800974015},
    {id:'glory_ak47', name:'Glory AK47', svg:'rifle', rarity:'mythical', price:usdToRastr(296.57), skinId:889710179},
    {id:'military_camo_mp5', name:'Military Camo MP5', svg:'rifle', rarity:'mythical', price:usdToRastr(233.32)},
    {id:'tempered_mask', name:'Tempered Mask', svg:'mask', rarity:'mythical', price:usdToRastr(197.15)},
    {id:'hot_tempered_longsword', name:'Hot-Tempered Longsword', svg:'knife', rarity:'mythical', price:usdToRastr(196.37)},
    {id:'glowing_skull', name:'Glowing Skull', svg:'mask', rarity:'mythical', price:usdToRastr(172.89)},
    {id:'christmas_lights', name:'Christmas Lights', svg:'default', rarity:'mythical', price:usdToRastr(160.11)},
    {id:'alien_red', name:'Alien Red', svg:'rifle', rarity:'mythical', price:usdToRastr(156.85), skinId:859845460},
    {id:'gold_rock', name:'Gold Rock', svg:'default', rarity:'mythical', price:usdToRastr(153.44)},
    {id:'stainless_facemask', name:'Stainless Facemask', svg:'mask', rarity:'mythical', price:usdToRastr(99.77)},
    {id:'legendary_gold_facemask', name:'Legendary Gold Facemask', svg:'mask', rarity:'mythical', price:usdToRastr(91.74)},
    {id:'plate_carrier_black', name:'Plate Carrier - Black', svg:'armor', rarity:'mythical', price:usdToRastr(88.04)},
    {id:'forest_raiders_roadsign_pants', name:'Forest Raiders Roadsign Pants', svg:'armor', rarity:'mythical', price:usdToRastr(84.66)},
    {id:'after_death_ar', name:'After Death AR', svg:'rifle', rarity:'mythical', price:usdToRastr(83.54), skinId:3529283241},
    {id:'desert_raiders_facemask', name:'Desert Raiders Facemask', svg:'mask', rarity:'mythical', price:usdToRastr(78.97)},
    {id:'tea_vending_machine', name:'Tea Vending Machine', svg:'default', rarity:'mythical', price:usdToRastr(71.86)},

    // 🔴 КРАСНІ (legendary)
    {id:'direct_threat_sap', name:'Direct Threat SAP', svg:'pistol', rarity:'legendary', price:usdToRastr(70.79)},
    {id:'desert_raiders_chest_plate', name:'Desert Raiders Chest Plate', svg:'armor', rarity:'legendary', price:usdToRastr(63.56)},
    {id:'forest_raiders_roadsign_vest', name:'Forest Raiders Roadsign Vest', svg:'armor', rarity:'legendary', price:usdToRastr(62.08)},
    {id:'ak_royale', name:'AK Royale', svg:'rifle', rarity:'legendary', price:usdToRastr(61.84), skinId:1359893925},
    {id:'space_rocket_work_gloves', name:'Space Rocket Work Gloves', svg:'armor', rarity:'legendary', price:usdToRastr(60.57)},
    {id:'shard_of_true_ice', name:'Shard of True Ice', svg:'gem', rarity:'legendary', price:usdToRastr(59.60)},
    {id:'forest_raiders_helmet', name:'Forest Raiders Helmet', svg:'helmet', rarity:'legendary', price:usdToRastr(59.35)},
    {id:'ak47_victoria', name:'AK-47 Victoria', svg:'rifle', rarity:'legendary', price:usdToRastr(54.75)},
    {id:'surgeon_scrubs', name:'Surgeon Scrubs', svg:'armor', rarity:'legendary', price:usdToRastr(52.27)},
    {id:'polymer_mp5', name:'Polymer MP5', svg:'rifle', rarity:'legendary', price:usdToRastr(50.10)},
    {id:'forest_raiders_roadsign_gloves', name:'Forest Raiders Roadsign Gloves', svg:'armor', rarity:'legendary', price:usdToRastr(42.06)},
    {id:'chop_shop_garage_door', name:'Chop Shop Garage Door', svg:'default', rarity:'legendary', price:usdToRastr(39.01)},
    {id:'howling_double_door', name:'Howling Double Door', svg:'default', rarity:'legendary', price:usdToRastr(37.58)},
    {id:'forest_raiders_pants', name:'Forest Raiders Pants', svg:'armor', rarity:'legendary', price:usdToRastr(36.61)},
    {id:'whiteout_helmet', name:'Whiteout Helmet', svg:'helmet', rarity:'legendary', price:usdToRastr(35.98)},
    {id:'cow_moo_flage_pants', name:'Cow Moo Flage Pants', svg:'armor', rarity:'legendary', price:usdToRastr(35.94)},
    {id:'double_door_from_hell', name:'Double Door From Hell', svg:'default', rarity:'legendary', price:usdToRastr(34.99)},
    {id:'no_mercy_jacket', name:'No Mercy Jacket', svg:'armor', rarity:'legendary', price:usdToRastr(34.75)},
    {id:'desert_raiders_pants', name:'Desert Raiders Pants', svg:'armor', rarity:'legendary', price:usdToRastr(33.97)},
    {id:'neon_boom_storage', name:'Neon Boom Storage', svg:'default', rarity:'legendary', price:usdToRastr(32.51)},
    {id:'rustige_egg_red', name:'Rustigé Egg - Red', svg:'gem', rarity:'legendary', price:usdToRastr(31.86)},
    {id:'checkpoint_riot_helmet', name:'Checkpoint Riot Helmet', svg:'helmet', rarity:'legendary', price:usdToRastr(31.53)},
    {id:'soviet_carpet', name:'Soviet Carpet', svg:'default', rarity:'legendary', price:usdToRastr(30.77), skinId:871072156},
    {id:'no_mercy_pants', name:'No Mercy Pants', svg:'armor', rarity:'legendary', price:usdToRastr(30.77)},
    {id:'ak47_from_hell', name:'AK-47 From Hell', svg:'rifle', rarity:'legendary', price:usdToRastr(29.18)},
    {id:'mystic_ak47', name:'Mystic AK47', svg:'rifle', rarity:'legendary', price:usdToRastr(29.15)},
    {id:'desert_raiders_roadsign_vest', name:'Desert Raiders Roadsign Vest', svg:'armor', rarity:'legendary', price:usdToRastr(29.01)},
    {id:'military_camo_roadsign_kilt', name:'Military Camo Roadsign Kilt', svg:'armor', rarity:'legendary', price:usdToRastr(28.60)},
    {id:'blackout_pants', name:'Blackout Pants', svg:'armor', rarity:'legendary', price:usdToRastr(27.41)},
    {id:'panda_rug', name:'Panda Rug', svg:'default', rarity:'legendary', price:usdToRastr(26.68), skinId:870446546},
    {id:'desert_raiders_hoodie', name:'Desert Raiders Hoodie', svg:'armor', rarity:'legendary', price:usdToRastr(26.23)},
    {id:'desert_raiders_helmet', name:'Desert Raiders Helmet', svg:'helmet', rarity:'legendary', price:usdToRastr(25.73)},
    {id:'press_vest', name:'Press Vest', svg:'armor', rarity:'legendary', price:usdToRastr(25.36)},
    {id:'dragon_glass_stone_hatchet', name:'Dragon Glass Stone Hatchet', svg:'axe', rarity:'legendary', price:usdToRastr(24.56)},
    {id:'blackout_hoodie', name:'Blackout Hoodie', svg:'armor', rarity:'legendary', price:usdToRastr(24.51)},
    {id:'skull_door_knocker', name:'Skull Door Knocker', svg:'default', rarity:'legendary', price:usdToRastr(24.02)},
    {id:'hot_tempered_revolver', name:'Hot-Tempered Revolver', svg:'pistol', rarity:'legendary', price:usdToRastr(23.36)},
    {id:'military_kilt', name:'Military Kilt', svg:'armor', rarity:'legendary', price:usdToRastr(23.09)},
    {id:'rat_mask', name:'Rat Mask', svg:'mask', rarity:'legendary', price:usdToRastr(22.97)},
    {id:'scorched_hammer', name:'Scorched Hammer', svg:'axe', rarity:'legendary', price:usdToRastr(22.63)},
    {id:'heat_double_shotgun', name:'Heat Double Shotgun', svg:'rifle', rarity:'legendary', price:usdToRastr(22.49)},
    {id:'wasteland_hunter_gloves', name:'Wasteland Hunter Gloves', svg:'armor', rarity:'legendary', price:usdToRastr(22.06), skinId:961103399},
    {id:'forest_raiders_facemask', name:'Forest Raiders Facemask', svg:'mask', rarity:'legendary', price:usdToRastr(21.26)},
    {id:'blackout_vest', name:'Blackout Vest', svg:'armor', rarity:'legendary', price:usdToRastr(21.04)},
    {id:'no_mercy_hoodie', name:'No Mercy Hoodie', svg:'armor', rarity:'legendary', price:usdToRastr(20.74)},
    {id:'whiteout_vest', name:'Whiteout Vest', svg:'armor', rarity:'legendary', price:usdToRastr(20.04)},
    {id:'whiteout_kilt', name:'Whiteout Kilt', svg:'armor', rarity:'legendary', price:usdToRastr(19.90)},
    {id:'polymer_pump_shotgun', name:'Polymer Pump Shotgun', svg:'rifle', rarity:'legendary', price:usdToRastr(19.52)},
    {id:'desert_raiders_roadsign_pants', name:'Desert Raiders Roadsign Pants', svg:'armor', rarity:'legendary', price:usdToRastr(19.44)},
    {id:'whiteout_facemask', name:'Whiteout Facemask', svg:'mask', rarity:'legendary', price:usdToRastr(19.33), skinId:2432948498},
    {id:'scientific_fuel_storage', name:'Scientific Fuel Storage', svg:'default', rarity:'legendary', price:usdToRastr(19.15)},
    {id:'playmaker_ak47', name:'Playmaker AK47', svg:'rifle', rarity:'legendary', price:usdToRastr(18.54)},
    {id:'glory_sar', name:'Glory SAR', svg:'rifle', rarity:'legendary', price:usdToRastr(18.49)},
    {id:'rox_black_vending_machine', name:'Rox Black Vending Machine', svg:'default', rarity:'legendary', price:usdToRastr(18.44)},
    {id:'army_bolt_rifle', name:'Army Bolt Rifle', svg:'rifle', rarity:'legendary', price:usdToRastr(18.42)},
    {id:'comics_ar', name:'Comics AR', svg:'rifle', rarity:'legendary', price:usdToRastr(18.39)},
    {id:'forest_raiders_hoodie', name:'Forest Raiders Hoodie', svg:'armor', rarity:'legendary', price:usdToRastr(18.25)},

    // 🟣 ФІОЛЕТОВІ (rare)
    {id:'tribesman_hide_pants', name:'Tribesman Hide Pants', svg:'armor', rarity:'rare', price:usdToRastr(18.21)},
    {id:'spacesuit', name:'Spacesuit', svg:'armor', rarity:'rare', price:usdToRastr(18.02)},
    {id:'forest_raiders_metal_chest_plate', name:'Forest Raiders Metal Chest Plate', svg:'armor', rarity:'rare', price:usdToRastr(17.98)},
    {id:'whiteout_hoodie', name:'Whiteout Hoodie', svg:'armor', rarity:'rare', price:usdToRastr(17.88)},
    {id:'comics_sar', name:'Comics SAR', svg:'rifle', rarity:'rare', price:usdToRastr(17.65)},
    {id:'cowboy_sheriff_hoodie', name:'Cowboy Sheriff Hoodie', svg:'armor', rarity:'rare', price:usdToRastr(17.50)},
    {id:'brutalist_sheet_metal_door', name:'Brutalist Sheet Metal Door', svg:'default', rarity:'rare', price:usdToRastr(17.11)},
    {id:'worker_pants', name:'Worker Pants', svg:'armor', rarity:'rare', price:usdToRastr(16.60)},
    {id:'furious_raider_riot_helmet', name:'Furious Raider Riot Helmet', svg:'helmet', rarity:'rare', price:usdToRastr(16.28)},
    {id:'box_from_hell', name:'Box From Hell', svg:'default', rarity:'rare', price:usdToRastr(15.72)},
    {id:'toxic', name:'Toxic', svg:'rifle', rarity:'rare', price:usdToRastr(15.70)},
    {id:'cargo_truck_garage_door', name:'Cargo Truck Garage Door', svg:'default', rarity:'rare', price:usdToRastr(15.68)},
    {id:'scientific_ammo_storage', name:'Scientific Ammo Storage', svg:'default', rarity:'rare', price:usdToRastr(15.53)},
    {id:'skeleton_hoodie', name:'Skeleton Hoodie', svg:'armor', rarity:'rare', price:usdToRastr(15.43)},
    {id:'arctic_protection_burlap_headwrap', name:'Arctic Protection Burlap Headwrap', svg:'armor', rarity:'rare', price:usdToRastr(15.25)},
    {id:'blackout_kilt', name:'Blackout Kilt', svg:'armor', rarity:'rare', price:usdToRastr(15.18)},
    {id:'rustige_egg_ivory', name:'Rustigé Egg - Ivory', svg:'gem', rarity:'rare', price:usdToRastr(15.14)},
    {id:'native_american_hide_shoes', name:'Native American Hide Shoes', svg:'armor', rarity:'rare', price:usdToRastr(14.95)},
    {id:'imp_sar', name:'IMP SAR', svg:'rifle', rarity:'rare', price:usdToRastr(14.87)},
    {id:'blackout_helmet', name:'Blackout Helmet', svg:'helmet', rarity:'rare', price:usdToRastr(14.67)},
    {id:'glory_thompson', name:'Glory Thompson', svg:'rifle', rarity:'rare', price:usdToRastr(14.63)},
    {id:'aztek_night_hunter', name:'Aztek Night Hunter', svg:'mask', rarity:'rare', price:usdToRastr(14.55)},
    {id:'blackout_gloves', name:'Blackout Gloves', svg:'armor', rarity:'rare', price:usdToRastr(14.27)},
    {id:'arctic_protection_burlap_shirt', name:'Arctic Protection Burlap Shirt', svg:'armor', rarity:'rare', price:usdToRastr(14.19)},
    {id:'rabbit_mask', name:'Rabbit Mask', svg:'mask', rarity:'rare', price:usdToRastr(14.08)},
    {id:'bombshell_sheet_metal_double_door', name:'Bombshell Sheet Metal Double Door', svg:'default', rarity:'rare', price:usdToRastr(13.92)},
    {id:'neon_drop_box_storage', name:'Neon Drop Box Storage', svg:'default', rarity:'rare', price:usdToRastr(13.69)},
    {id:'cowboy_sheriff_pants', name:'Cowboy Sheriff Pants', svg:'armor', rarity:'rare', price:usdToRastr(13.53)},
    {id:'spooky_slime_furnace', name:'Spooky Slime Furnace', svg:'default', rarity:'rare', price:usdToRastr(13.49)},
    {id:'neon_ore_storage', name:'Neon Ore Storage', svg:'default', rarity:'rare', price:usdToRastr(13.37)},
    {id:'desert_patrol_vest', name:'Desert Patrol Vest', svg:'armor', rarity:'rare', price:usdToRastr(13.31)},
    {id:'no_mercy_facemask', name:'No Mercy Facemask', svg:'mask', rarity:'rare', price:usdToRastr(13.28)},
    {id:'military_vest', name:'Military Vest', svg:'armor', rarity:'rare', price:usdToRastr(12.89)},
    {id:'aztec_long_t_shirt', name:'Aztec Long T-Shirt', svg:'armor', rarity:'rare', price:usdToRastr(12.79)},
    {id:'cold_hunter_mp5', name:'Cold Hunter MP5', svg:'rifle', rarity:'rare', price:usdToRastr(12.76)},
    {id:'blackout_boots', name:'Blackout Boots', svg:'armor', rarity:'rare', price:usdToRastr(12.70)},
    {id:'uprising_hide_poncho', name:'Uprising Hide Poncho', svg:'armor', rarity:'rare', price:usdToRastr(12.52)},
    {id:'neon_scrap_storage', name:'Neon Scrap Storage', svg:'default', rarity:'rare', price:usdToRastr(12.36)},
    {id:'reptile_hunter_facemask', name:'Reptile Hunter Facemask', svg:'mask', rarity:'rare', price:usdToRastr(12.31)},
    {id:'snow_warrior_hoodie', name:'Snow Warrior Hoodie', svg:'armor', rarity:'rare', price:usdToRastr(12.26)},
    {id:'portable_toilet', name:'Portable Toilet', svg:'default', rarity:'rare', price:usdToRastr(12.22)},
    {id:'cobalt_container_double_door', name:'Cobalt Container Double Door', svg:'default', rarity:'rare', price:usdToRastr(11.73)},
    {id:'high_quality_bag', name:'High Quality Bag', svg:'armor', rarity:'rare', price:usdToRastr(11.66)},
    {id:'labyrinth_door', name:'Labyrinth Door', svg:'default', rarity:'rare', price:usdToRastr(11.48)},
    {id:'silver_leaf_hammer', name:'Silver Leaf Hammer', svg:'axe', rarity:'rare', price:usdToRastr(11.47)},
    {id:'kiss_ar', name:'Kiss AR', svg:'rifle', rarity:'rare', price:usdToRastr(11.34)},
    {id:'savage_facemask', name:'Savage Facemask', svg:'mask', rarity:'rare', price:usdToRastr(11.16)},
    {id:'legacy_bow', name:'Legacy Bow', svg:'crossbow', rarity:'rare', price:usdToRastr(11.11)},
    {id:'training_pants', name:'Training Pants', svg:'armor', rarity:'rare', price:usdToRastr(11.10)},
    {id:'digger_helmet', name:'Digger Helmet', svg:'helmet', rarity:'rare', price:usdToRastr(11.05)},
    {id:'scavenger_facemask', name:'Scavenger Facemask', svg:'mask', rarity:'rare', price:usdToRastr(11.04)},
    {id:'fisherman_burlap_pants', name:'Fisherman Burlap Pants', svg:'armor', rarity:'rare', price:usdToRastr(11.02)},
    {id:'neon_clothes_storage', name:'Neon Clothes Storage', svg:'default', rarity:'rare', price:usdToRastr(11.01)},
    {id:'red_leather_chair', name:'Red Leather Chair', svg:'default', rarity:'rare', price:usdToRastr(11.01)},
    {id:'elite_forest_camo_hoodie', name:'Elite Forest Camo Hoodie', svg:'armor', rarity:'rare', price:usdToRastr(10.85)},
    {id:'black_acoustic_guitar', name:'Black Acoustic Guitar', svg:'default', rarity:'rare', price:usdToRastr(10.83)},
    {id:'cold_hunter_ak', name:'Cold Hunter AK', svg:'rifle', rarity:'rare', price:usdToRastr(10.83)},
    {id:'vandals_peace_door', name:'Vandal\'s Peace Door', svg:'default', rarity:'rare', price:usdToRastr(10.74)},
    {id:'neon_sign_pack', name:'Neon Sign Pack', svg:'default', rarity:'rare', price:usdToRastr(10.67)},
    {id:'scientific_electrical_storage', name:'Scientific Electrical Storage', svg:'default', rarity:'rare', price:usdToRastr(10.62)},
    {id:'tempered_ak47', name:'Tempered AK47', svg:'rifle', rarity:'rare', price:usdToRastr(10.55), skinId:566540646},
    {id:'protector_sheet_metal_double_door', name:'Protector Sheet Metal Double Door', svg:'default', rarity:'rare', price:usdToRastr(10.50)},
    {id:'comics_hoodie', name:'Comics Hoodie', svg:'armor', rarity:'rare', price:usdToRastr(10.50)},
    {id:'neon_elec_storage', name:'Neon Elec Storage', svg:'default', rarity:'rare', price:usdToRastr(10.38)},
    {id:'addicted_guitarist', name:'Addicted Guitarist', svg:'default', rarity:'rare', price:usdToRastr(10.33)},
    {id:'heat_seeker_thompson', name:'Heat Seeker Thompson', svg:'rifle', rarity:'rare', price:usdToRastr(10.22)},
    {id:'christmas_locker', name:'Christmas Locker', svg:'default', rarity:'rare', price:usdToRastr(10.16)},
    {id:'military_roadsign_gloves', name:'Military Roadsign Gloves', svg:'armor', rarity:'rare', price:usdToRastr(10.06)},
    {id:'knight_templar_kilt', name:'Knight Templar Kilt', svg:'armor', rarity:'rare', price:usdToRastr(9.96)},
    {id:'neon_wood_storage', name:'Neon Wood Storage', svg:'default', rarity:'rare', price:usdToRastr(9.94)},
    {id:'dark_silver_python', name:'Dark Silver Python', svg:'pistol', rarity:'rare', price:usdToRastr(9.89)},
    {id:'grey_wolf_hide_poncho', name:'Grey Wolf Hide Poncho', svg:'armor', rarity:'rare', price:usdToRastr(9.88)},
    {id:'greening_area_double_door', name:'Greening Area Double Door', svg:'default', rarity:'rare', price:usdToRastr(9.87)},
    {id:'predator_pants', name:'Predator Pants', svg:'armor', rarity:'rare', price:usdToRastr(9.86)},
    {id:'stinger_icepick', name:'Stinger Icepick', svg:'axe', rarity:'rare', price:usdToRastr(9.82)},
    {id:'farmer_overalls_bottom', name:'Farmer Overalls Bottom', svg:'armor', rarity:'rare', price:usdToRastr(9.82)},
    {id:'blackout_bow', name:'Blackout Bow', svg:'crossbow', rarity:'rare', price:usdToRastr(9.82)},
    {id:'no_mercy_gloves', name:'No Mercy Gloves', svg:'armor', rarity:'rare', price:usdToRastr(9.79)},
    {id:'cobalt_personal_locker', name:'Cobalt Personal Locker', svg:'default', rarity:'rare', price:usdToRastr(9.79)},
    {id:'desert_patrol_helmet', name:'Desert Patrol Helmet', svg:'helmet', rarity:'rare', price:usdToRastr(9.78)},

    // 🔵 СИНІ (common)
    {id:'training_hoodie', name:'Training Hoodie', svg:'armor', rarity:'common', price:usdToRastr(9.77)},
    {id:'cargo_heli_storage', name:'Cargo Heli Storage', svg:'default', rarity:'common', price:usdToRastr(9.72)},
    {id:'army_facemask', name:'Army Facemask', svg:'mask', rarity:'common', price:usdToRastr(9.63)},
    {id:'tools_supply_container', name:'Tools Supply Container', svg:'default', rarity:'common', price:usdToRastr(9.51)},
    {id:'burglar_mask', name:'Burglar Mask', svg:'mask', rarity:'common', price:usdToRastr(9.47)},
    {id:'tribesman_hide_shirt', name:'Tribesman Hide Shirt', svg:'armor', rarity:'common', price:usdToRastr(9.47)},
    {id:'blackout_jacket', name:'Blackout Jacket', svg:'armor', rarity:'common', price:usdToRastr(9.40)},
    {id:'jpeg_roadsign_gloves', name:'JPEG Roadsign Gloves', svg:'armor', rarity:'common', price:usdToRastr(9.36)},
    {id:'bombshell_m249', name:'Bombshell M249', svg:'rifle', rarity:'common', price:usdToRastr(9.32)},
    {id:'military_helmet', name:'Military Helmet', svg:'helmet', rarity:'common', price:usdToRastr(9.30)},
    {id:'army_armored_helmet', name:'Army Armored Helmet', svg:'helmet', rarity:'common', price:usdToRastr(9.23)},
    {id:'desert_patrol_pants', name:'Desert Patrol Pants', svg:'armor', rarity:'common', price:usdToRastr(9.22)},
    {id:'beauty_industry_double_door', name:'Beauty Industry Double Door', svg:'default', rarity:'common', price:usdToRastr(9.21)},
    {id:'brutalist_garage_door', name:'Brutalist Garage Door', svg:'default', rarity:'common', price:usdToRastr(9.18)},
    {id:'burlap_bandit_shirt', name:'Burlap Bandit Shirt', svg:'armor', rarity:'common', price:usdToRastr(9.13)},
    {id:'popstar', name:'Popstar', svg:'rifle', rarity:'common', price:usdToRastr(9.12)},
    {id:'thundergold_helmet', name:'Thundergold Helmet', svg:'helmet', rarity:'common', price:usdToRastr(9.00)},
    {id:'neon_bismuth_metal_double_door', name:'Neon Bismuth Metal Double Door', svg:'default', rarity:'common', price:usdToRastr(8.97)},
    {id:'abyss_metal_double_door', name:'Abyss Metal Double Door', svg:'default', rarity:'common', price:usdToRastr(8.93)},
    {id:'operator_helmet', name:'Operator Helmet', svg:'helmet', rarity:'common', price:usdToRastr(8.92)},
    {id:'scientific_guns_storage', name:'Scientific Guns Storage', svg:'default', rarity:'common', price:usdToRastr(8.88)},
    {id:'redemption_kilt', name:'Redemption Kilt', svg:'armor', rarity:'common', price:usdToRastr(8.88)},
    {id:'whiteout_pants', name:'Whiteout Pants', svg:'armor', rarity:'common', price:usdToRastr(8.88)},
    {id:'knights_templar_facemask', name:'Knights Templar Facemask', svg:'mask', rarity:'common', price:usdToRastr(8.81)},
    {id:'blue_tarp_skirt', name:'Blue Tarp Skirt', svg:'armor', rarity:'common', price:usdToRastr(8.71)},
    {id:'forest_raiders_boots', name:'Forest Raiders Boots', svg:'armor', rarity:'common', price:usdToRastr(8.69)},
    {id:'kayak_helmet', name:'Kayak Helmet', svg:'helmet', rarity:'common', price:usdToRastr(8.66)},
    {id:'boxers_bandages', name:'Boxer\'s Bandages', svg:'armor', rarity:'common', price:usdToRastr(8.62)},
    {id:'urban_night_door', name:'Urban Night Door', svg:'default', rarity:'common', price:usdToRastr(8.60)},
    {id:'reptile_hunter_chestplate', name:'Reptile Hunter Chestplate', svg:'armor', rarity:'common', price:usdToRastr(8.59)},
    {id:'crypt_armored_double_door', name:'Crypt Armored Double Door', svg:'default', rarity:'common', price:usdToRastr(8.59), skinId:2254750609},
    {id:'popstar_garage_door', name:'Popstar Garage Door', svg:'default', rarity:'common', price:usdToRastr(8.57)},
    {id:'arctic_protection_burlap_pants', name:'Arctic Protection Burlap Pants', svg:'armor', rarity:'common', price:usdToRastr(8.46)},
    {id:'thundergold_roadsign_kilt', name:'Thundergold Roadsign Kilt', svg:'armor', rarity:'common', price:usdToRastr(8.41)},
    {id:'polymer_bar', name:'Polymer Bar', svg:'rifle', rarity:'common', price:usdToRastr(8.34)},
    {id:'training_kilt', name:'Training Kilt', svg:'armor', rarity:'common', price:usdToRastr(8.32)},
    {id:'phantom_hoodie', name:'Phantom Hoodie', svg:'armor', rarity:'common', price:usdToRastr(8.31)},
    {id:'whiteout_roadsign_gloves', name:'Whiteout Roadsign Gloves', svg:'armor', rarity:'common', price:usdToRastr(8.29)},
    {id:'weapon_barrel', name:'Weapon Barrel', svg:'default', rarity:'common', price:usdToRastr(8.17)},
    {id:'cargo_heli_locker', name:'Cargo Heli Locker', svg:'default', rarity:'common', price:usdToRastr(8.10)},
    {id:'jack_sheet_metal_double_door', name:'Jack Sheet Metal Double Door', svg:'default', rarity:'common', price:usdToRastr(8.04)},
    {id:'uprising_hide_shoes', name:'Uprising Hide Shoes', svg:'armor', rarity:'common', price:usdToRastr(8.04)},
    {id:'comics_jackhammer', name:'Comics Jackhammer', svg:'axe', rarity:'common', price:usdToRastr(8.04)},
    {id:'forest_camouflage_net', name:'Forest Camouflage Net', svg:'default', rarity:'common', price:usdToRastr(8.01)},
    {id:'hellcore_thompson', name:'Hellcore Thompson', svg:'rifle', rarity:'common', price:usdToRastr(8.00)},
    {id:'forest_camo_bag', name:'Forest Camo Bag', svg:'armor', rarity:'common', price:usdToRastr(7.96)},
    {id:'cobalt_coffee', name:'Cobalt Coffee', svg:'default', rarity:'common', price:usdToRastr(7.95)},
    {id:'knights_templar_hoodie', name:'Knights Templar Hoodie', svg:'armor', rarity:'common', price:usdToRastr(7.92)},
    {id:'batteries_not_included', name:'Batteries Not Included', svg:'rifle', rarity:'common', price:usdToRastr(7.90)},
    {id:'fisherman_burlap_shirt', name:'Fisherman Burlap Shirt', svg:'armor', rarity:'common', price:usdToRastr(7.87)},
    {id:'volcanic_stone_hatchet', name:'Volcanic Stone Hatchet', svg:'axe', rarity:'common', price:usdToRastr(7.87)},
    {id:'space_station_armored_double_door', name:'Space Station Armored Double Door', svg:'default', rarity:'common', price:usdToRastr(7.87)},
    {id:'going_deep_garage_door', name:'Going Deep Garage Door', svg:'default', rarity:'common', price:usdToRastr(7.87)},
    {id:'sleazy_rider', name:'Sleazy Rider', svg:'armor', rarity:'common', price:usdToRastr(7.86)},
    {id:'cardboard_kilt', name:'Cardboard Kilt', svg:'armor', rarity:'common', price:usdToRastr(7.86)},
    {id:'grass_rug', name:'Grass Rug', svg:'default', rarity:'common', price:usdToRastr(7.84)},
    {id:'survivor_lr300', name:'Survivor LR-300', svg:'rifle', rarity:'common', price:usdToRastr(7.75)},
    {id:'glory_mask', name:'Glory Mask', svg:'mask', rarity:'common', price:usdToRastr(7.71)},
    {id:'cow_moo_flage_gloves', name:'Cow Moo Flage Gloves', svg:'armor', rarity:'common', price:usdToRastr(7.68)},
    {id:'whiteout_chestplate', name:'Whiteout Chestplate', svg:'armor', rarity:'common', price:usdToRastr(7.67)},
    {id:'blackout_python', name:'Blackout Python', svg:'pistol', rarity:'common', price:usdToRastr(7.66)},
    {id:'sakura_ar', name:'Sakura AR', svg:'rifle', rarity:'common', price:usdToRastr(7.65)},
    {id:'urban_ice_hoodie', name:'Urban Ice Hoodie', svg:'armor', rarity:'common', price:usdToRastr(7.62)},
    {id:'no_mercy_ak47', name:'No Mercy AK47', svg:'rifle', rarity:'common', price:usdToRastr(7.58)},
    {id:'salvaged_plating_armor', name:'Salvaged Plating Armor', svg:'armor', rarity:'common', price:usdToRastr(7.56)},
    {id:'predator_hoodie', name:'Predator Hoodie', svg:'armor', rarity:'common', price:usdToRastr(7.54)},
    {id:'big_burger', name:'Big Burger', svg:'medkit', rarity:'common', price:usdToRastr(7.54)},
    {id:'urban_vending_machine', name:'Urban Vending Machine', svg:'default', rarity:'common', price:usdToRastr(7.53)},
    {id:'faded_sap', name:'Faded SAP', svg:'pistol', rarity:'common', price:usdToRastr(7.51)},
    {id:'cowboy_sheriff_hat', name:'Cowboy Sheriff Hat', svg:'armor', rarity:'common', price:usdToRastr(7.51)},
    {id:'desert_conqueror_hoodie', name:'Desert Conqueror Hoodie', svg:'armor', rarity:'common', price:usdToRastr(7.51)},
    {id:'military_facemask', name:'Military Facemask', svg:'mask', rarity:'common', price:usdToRastr(7.51)},
    {id:'scientific_gunpowder_storage', name:'Scientific Gunpowder Storage', svg:'default', rarity:'common', price:usdToRastr(7.49)},
    {id:'danger_fork', name:'Danger Fork', svg:'knife', rarity:'common', price:usdToRastr(7.42)},
    {id:'bee_cosplay_facemask', name:'Bee Cosplay Facemask', svg:'mask', rarity:'common', price:usdToRastr(7.39)},
    {id:'farmer_straw_hat', name:'Farmer Straw Hat', svg:'armor', rarity:'common', price:usdToRastr(7.34)},
    {id:'homemade_shorts', name:'Homemade Shorts', svg:'armor', rarity:'common', price:usdToRastr(7.33)},
    {id:'ancient_gods_furnace', name:'Ancient Gods Furnace', svg:'default', rarity:'common', price:usdToRastr(7.32)},
    {id:'fireflies_metal_door', name:'Fireflies Metal Door', svg:'default', rarity:'common', price:usdToRastr(7.30)},
    {id:'fish_shoes', name:'Fish Shoes', svg:'armor', rarity:'common', price:usdToRastr(7.30)},
    {id:'black_gold_kilt', name:'Black Gold Kilt', svg:'armor', rarity:'common', price:usdToRastr(7.29)},
    {id:'blackout_facemask', name:'Blackout Facemask', svg:'mask', rarity:'common', price:usdToRastr(7.25)},
    {id:'uprising_stone_pickaxe', name:'Uprising Stone Pickaxe', svg:'axe', rarity:'common', price:usdToRastr(7.21)},
    {id:'neon_bismuth_armored_double_door', name:'Neon Bismuth Armored Double Door', svg:'default', rarity:'common', price:usdToRastr(7.19)},
    {id:'training_gloves', name:'Training Gloves', svg:'armor', rarity:'common', price:usdToRastr(7.14)},
    {id:'reptile_hunter_vest', name:'Reptile Hunter Vest', svg:'armor', rarity:'common', price:usdToRastr(7.12)},
    {id:'bee_cosplay_chestplate', name:'Bee Cosplay Chestplate', svg:'armor', rarity:'common', price:usdToRastr(7.11)},
    {id:'pirate_sheet_metal_door', name:'Pirate Sheet Metal Door', svg:'default', rarity:'common', price:usdToRastr(7.09)},
    {id:'rusty_bucket_helmet', name:'Rusty Bucket Helmet', svg:'helmet', rarity:'common', price:usdToRastr(7.07)},
    {id:'blackout_ar', name:'Blackout AR', svg:'rifle', rarity:'common', price:usdToRastr(7.05)},
    {id:'easter_chick_hammer', name:'Easter Chick Hammer', svg:'axe', rarity:'common', price:usdToRastr(7.00)},
    {id:'heat_seeker_revolver', name:'Heat Seeker Revolver', svg:'pistol', rarity:'common', price:usdToRastr(6.99)},
    {id:'mummy_wraps', name:'Mummy Wraps', svg:'armor', rarity:'common', price:usdToRastr(6.97)},
    {id:'bombshell_sheet_metal_door', name:'Bombshell Sheet Metal Door', svg:'default', rarity:'common', price:usdToRastr(6.97)},
    {id:'no_mercy_helmet', name:'No Mercy Helmet', svg:'helmet', rarity:'common', price:usdToRastr(6.96)},
    {id:'flower_hat', name:'Flower Hat', svg:'armor', rarity:'common', price:usdToRastr(6.95)},
    {id:'yellow_police_jacket', name:'Yellow Police Jacket', svg:'armor', rarity:'common', price:usdToRastr(6.91)},
    {id:'bombshell_garage_door', name:'Bombshell Garage Door', svg:'default', rarity:'common', price:usdToRastr(6.91)},
    {id:'glory_gloves', name:'Glory Gloves', svg:'armor', rarity:'common', price:usdToRastr(6.90)},
    {id:'cardboard_helmet', name:'Cardboard Helmet', svg:'helmet', rarity:'common', price:usdToRastr(6.90)},
    {id:'lavapick', name:'Lavapick', svg:'axe', rarity:'common', price:usdToRastr(6.88)},
    {id:'porcelain_ar', name:'Porcelain AR', svg:'rifle', rarity:'common', price:usdToRastr(6.87)},
    {id:'spooky_speaker', name:'Spooky Speaker', svg:'default', rarity:'common', price:usdToRastr(6.86)},
    {id:'polished_obsidian_furnace', name:'Polished Obsidian Furnace', svg:'default', rarity:'common', price:usdToRastr(6.78)},
    {id:'blackout_mp5', name:'Blackout MP5', svg:'rifle', rarity:'common', price:usdToRastr(6.74)},
    {id:'carbon_facemask', name:'Carbon Facemask', svg:'mask', rarity:'common', price:usdToRastr(6.73)},
    {id:'pirate_bed', name:'Pirate Bed', svg:'default', rarity:'common', price:usdToRastr(6.72)},
    {id:'uap_pilot_sleeping_bag', name:'UAP Pilot Sleeping Bag', svg:'default', rarity:'common', price:usdToRastr(6.72)},
    {id:'no_mercy_garage_door', name:'No Mercy Garage Door', svg:'default', rarity:'common', price:usdToRastr(6.69)},
    {id:'tactical_leather_gloves', name:'Tactical Leather Gloves', svg:'armor', rarity:'common', price:usdToRastr(6.69)},
    {id:'metalhead_m39', name:'Metalhead M39', svg:'rifle', rarity:'common', price:usdToRastr(6.68)},
    {id:'neon_frags_storage', name:'Neon Frags Storage', svg:'default', rarity:'common', price:usdToRastr(6.65)},
    {id:'no_mercy_kilt', name:'No Mercy Kilt', svg:'armor', rarity:'common', price:usdToRastr(6.63)},
    {id:'no_mercy_mp5', name:'No Mercy MP5', svg:'rifle', rarity:'common', price:usdToRastr(6.58)},
    {id:'aztec_jade_hachet', name:'Aztec Jade Hachet', svg:'axe', rarity:'common', price:usdToRastr(6.57)},
    {id:'urban_light_sar', name:'Urban Light SAR', svg:'rifle', rarity:'common', price:usdToRastr(6.57)},
    {id:'abyss_sleeping_bag', name:'Abyss Sleeping Bag', svg:'default', rarity:'common', price:usdToRastr(6.55)},
    {id:'comics_sleeping_bag', name:'Comics Sleeping Bag', svg:'default', rarity:'common', price:usdToRastr(6.53)},
    {id:'neon_charcoal_storage', name:'Neon Charcoal Storage', svg:'default', rarity:'common', price:usdToRastr(6.49)},
    {id:'wasteland_hunter_hoodie', name:'Wasteland Hunter Hoodie', svg:'armor', rarity:'common', price:usdToRastr(6.46)},
    {id:'elite_forest_camo_pants', name:'Elite Forest Camo Pants', svg:'armor', rarity:'common', price:usdToRastr(6.45)},
    {id:'thundergold_facemask', name:'Thundergold Facemask', svg:'mask', rarity:'common', price:usdToRastr(6.39)},
    {id:'desert_conqueror_pants', name:'Desert Conqueror Pants', svg:'armor', rarity:'common', price:usdToRastr(6.39)},
    {id:'cobalt_container_metal_door', name:'Cobalt Container Metal Door', svg:'default', rarity:'common', price:usdToRastr(6.38)},
    {id:'sand_rhino_facemask', name:'Sand Rhino Facemask', svg:'mask', rarity:'common', price:usdToRastr(6.38)},
    {id:'military_chestplate', name:'Military Chestplate', svg:'armor', rarity:'common', price:usdToRastr(6.36)},
    {id:'abyss_boots', name:'Abyss Boots', svg:'armor', rarity:'common', price:usdToRastr(6.35)},
    {id:'neon_pumpkin_metal_double_door', name:'Neon Pumpkin Metal Double Door', svg:'default', rarity:'common', price:usdToRastr(6.34)},
    {id:'tea_ceremony_knife', name:'Tea Ceremony Knife', svg:'knife', rarity:'common', price:usdToRastr(6.30)},
    {id:'reptile_hunter_large_backpack', name:'Reptile Hunter Large Backpack', svg:'armor', rarity:'common', price:usdToRastr(6.29)},
    {id:'black_diamond_pants', name:'Black Diamond Pants', svg:'armor', rarity:'common', price:usdToRastr(6.29)},
    {id:'greening_area_garage_door', name:'Greening Area Garage Door', svg:'default', rarity:'common', price:usdToRastr(6.27)},
    {id:'furnace_from_hell', name:'Furnace From Hell', svg:'default', rarity:'common', price:usdToRastr(6.25)},
    {id:'rainbow_pony_ar', name:'Rainbow Pony AR', svg:'rifle', rarity:'common', price:usdToRastr(6.25)},
    {id:'anubis_ak47', name:'Anubis AK47', svg:'rifle', rarity:'common', price:usdToRastr(6.24)},
    {id:'battle_scarred_aks47', name:'Battle-Scarred AKS47', svg:'rifle', rarity:'common', price:usdToRastr(6.21)},
    {id:'dragon_rage_hoodie', name:'Dragon Rage Hoodie', svg:'armor', rarity:'common', price:usdToRastr(6.18)},
    {id:'heavenly_legion_kilt', name:'Heavenly Legion Kilt', svg:'armor', rarity:'common', price:usdToRastr(6.16)},
    {id:'knights_templar_chestplate', name:'Knights Templar Chestplate', svg:'armor', rarity:'common', price:usdToRastr(6.16)},
    {id:'wasteland_hunter_pants', name:'Wasteland Hunter Pants', svg:'armor', rarity:'common', price:usdToRastr(6.15)},
    {id:'hazard_semi_auto_rifle', name:'Hazard Semi Auto Rifle', svg:'rifle', rarity:'common', price:usdToRastr(6.15)},
    {id:'flashbacks_helmet', name:'Flashbacks Helmet', svg:'helmet', rarity:'common', price:usdToRastr(6.13)},
    {id:'nordic_beast_kilt', name:'Nordic Beast Kilt', svg:'armor', rarity:'common', price:usdToRastr(6.13)},
    {id:'wasteland_hunter_boots', name:'Wasteland Hunter Boots', svg:'armor', rarity:'common', price:usdToRastr(6.10)},
    {id:'cyber_core_mp5', name:'Cyber Core MP5', svg:'rifle', rarity:'common', price:usdToRastr(6.08)},
    {id:'bandit_rug', name:'Bandit Rug', svg:'default', rarity:'common', price:usdToRastr(6.07)},
    {id:'ancient_totem_furnace', name:'Ancient Totem Furnace', svg:'default', rarity:'common', price:usdToRastr(6.07)},
    {id:'black_gold_m249', name:'Black Gold M249', svg:'rifle', rarity:'common', price:usdToRastr(6.02)},
    {id:'phantom_lr300', name:'Phantom LR-300', svg:'rifle', rarity:'common', price:usdToRastr(5.98)},
    {id:'road_romeo_helmet', name:'Road Romeo Helmet', svg:'helmet', rarity:'common', price:usdToRastr(5.98)},
    {id:'rust_goalkeeper_shorts', name:'Rust Goalkeeper Shorts', svg:'armor', rarity:'common', price:usdToRastr(5.97)},
    {id:'azul_ak47', name:'Azul AK47', svg:'rifle', rarity:'common', price:usdToRastr(5.97)},
    {id:'flashbacks_pants', name:'Flashbacks Pants', svg:'armor', rarity:'common', price:usdToRastr(5.93)},
    {id:'twisted_metal_double_door', name:'Twisted Metal Double Door', svg:'default', rarity:'common', price:usdToRastr(5.92)},
    {id:'dungeon_garage_door', name:'Dungeon Garage Door', svg:'default', rarity:'common', price:usdToRastr(5.91)},
    {id:'skull_bandana', name:'Skull Bandana', svg:'mask', rarity:'common', price:usdToRastr(5.89)},
    {id:'black_diamond_gloves', name:'Black Diamond Gloves', svg:'armor', rarity:'common', price:usdToRastr(5.85)},
    {id:'glorious_ak', name:'Glorious AK', svg:'rifle', rarity:'common', price:usdToRastr(5.82)},
    {id:'tiger_mask', name:'Tiger Mask', svg:'mask', rarity:'common', price:usdToRastr(5.82)},
    {id:'full_metal_helmet', name:'Full Metal Helmet', svg:'helmet', rarity:'common', price:usdToRastr(5.80)},

    // МІНІМАЛЬНІ (для покриття множників x1.5-x2)
    {id:'rock', name:'Камень', svg:'default', rarity:'common', price:usdToRastr(0.10)},
    {id:'torch', name:'Факел', svg:'default', rarity:'common', price:usdToRastr(0.15)},
    {id:'bandage', name:'Бинты', svg:'medkit', rarity:'common', price:usdToRastr(0.20)},
    {id:'revolver_basic', name:'Револьвер', svg:'pistol', rarity:'common', price:usdToRastr(0.50)},
    {id:'wooden_spear', name:'Деревянное копьё', svg:'rifle', rarity:'common', price:usdToRastr(0.80)},
    {id:'stone_hatchet_basic', name:'Каменный топор', svg:'axe', rarity:'common', price:usdToRastr(1.00)},
    {id:'bow_basic', name:'Лук', svg:'crossbow', rarity:'common', price:usdToRastr(1.50)},
    {id:'crossbow_basic', name:'Арбалет', svg:'crossbow', rarity:'common', price:usdToRastr(2.00)},
    {id:'bone_knife', name:'Костяной нож', svg:'knife', rarity:'common', price:usdToRastr(2.50)},
    {id:'stone_spear', name:'Каменное копьё', svg:'rifle', rarity:'common', price:usdToRastr(3.00)},
    {id:'eoka_pistol', name:'Eoka Pistol', svg:'pistol', rarity:'common', price:usdToRastr(3.50)},
    {id:'waterpipe_shotgun', name:'Водопроводный дробовик', svg:'rifle', rarity:'common', price:usdToRastr(4.00)},
    {id:'semi_auto_pistol', name:'Semi-Auto Pistol', svg:'pistol', rarity:'common', price:usdToRastr(4.50)},
    {id:'compound_bow', name:'Составной лук', svg:'crossbow', rarity:'common', price:usdToRastr(5.00)}
];

// Експорт для script.js
var SKIN_BY_ID = {};
SKINS.forEach(function(s){ SKIN_BY_ID[s.id] = s; });
function resolveSkin(item) {
    if (!item) return null;
    return SKIN_BY_ID[item.id] || item;
}
