// lib/skins.js
// Серверний каталог скінів. Джерело істини для цін і апгрейдів.

module.exports = [
  // --- ЗБРОЯ ---
  { id: 'tempered_ak47', name: 'Tempered AK47', shortname: 'rifle.ak', rarity: 'rare', price: 11.47 },
  { id: 'alien_red', name: 'Alien Red', shortname: 'rifle.ak', rarity: 'mythical', price: 172.00 },
  { id: 'glory_ak47', name: 'Glory AK47', shortname: 'rifle.ak', rarity: 'mythical', price: 259.00 },
  { id: 'after_death_ar', name: 'After Death AR', shortname: 'rifle.ak', rarity: 'mythical', price: 114.00 },
  { id: 'azul_ak47', name: 'Azul AK47', shortname: 'rifle.ak', rarity: 'common', price: 4.94 },
  { id: 'battle_scarred_aks47', name: 'Battle-Scarred AKS47', shortname: 'rifle.ak', rarity: 'common', price: 8.65 },
  { id: 'anubis_ak47', name: 'Anubis AK47', shortname: 'rifle.ak', rarity: 'common', price: 8.84 },
  { id: 'rainbow_pony_ar', name: 'Rainbow Pony AR', shortname: 'rifle.ak', rarity: 'common', price: 9.03 },
  { id: 'blackout_ar', name: 'Blackout AR', shortname: 'rifle.ak', rarity: 'common', price: 17.39 },
  { id: 'sakura_ar', name: 'Sakura AR', shortname: 'rifle.ak', rarity: 'common', price: 22.52 },
  { id: 'batteries_not_included', name: 'Batteries Not Included', shortname: 'rifle.ak', rarity: 'common', price: 24.99 },
  { id: 'popstar', name: 'Popstar', shortname: 'rifle.ak', rarity: 'common', price: 31.26 },
  { id: 'kiss_ar', name: 'Kiss AR', shortname: 'rifle.ak', rarity: 'rare', price: 147.00 },
  { id: 'toxic', name: 'Toxic', shortname: 'rifle.ak', rarity: 'rare', price: 1185.00 },
  { id: 'comics_ar', name: 'Comics AR', shortname: 'rifle.ak', rarity: 'legendary', price: 2300.00 },
  { id: 'playmaker_ak47', name: 'Playmaker AK47', shortname: 'rifle.ak', rarity: 'legendary', price: 2700.00 },
  { id: 'ak_royale', name: 'AK Royale', shortname: 'rifle.ak', rarity: 'legendary', price: 74000.00 },
  { id: 'ak47_victoria', name: 'AK-47 Victoria', shortname: 'rifle.ak', rarity: 'legendary', price: 55400.00 },
  { id: 'ak47_from_hell', name: 'AK-47 From Hell', shortname: 'rifle.ak', rarity: 'legendary', price: 15600.00 },
  { id: 'mystic_ak47', name: 'Mystic AK47', shortname: 'rifle.ak', rarity: 'legendary', price: 14500.00 },

  // --- SMG ---
  { id: 'cyber_core_mp5', name: 'Cyber Core MP5', shortname: 'smg.mp5', rarity: 'common', price: 6.94 },
  { id: 'no_mercy_mp5', name: 'No Mercy MP5', shortname: 'smg.mp5', rarity: 'common', price: 12.83 },
  { id: 'blackout_mp5', name: 'Blackout MP5', shortname: 'smg.mp5', rarity: 'common', price: 14.54 },
  { id: 'hellcore_thompson', name: 'Hellcore Thompson', shortname: 'smg.thompson', rarity: 'common', price: 25.75 },
  { id: 'heat_seeker_thompson', name: 'Heat Seeker Thompson', shortname: 'smg.thompson', rarity: 'rare', price: 52.00 },
  { id: 'glory_thompson', name: 'Glory Thompson', shortname: 'smg.thompson', rarity: 'rare', price: 664.00 },
  { id: 'cold_hunter_mp5', name: 'Cold Hunter MP5', shortname: 'smg.mp5', rarity: 'rare', price: 286.00 },
  { id: 'polymer_mp5', name: 'Polymer MP5', shortname: 'smg.mp5', rarity: 'legendary', price: 47800.00 },
  { id: 'military_camo_mp5', name: 'Military Camo MP5', shortname: 'smg.mp5', rarity: 'mythical', price: 242000.00 },
  { id: 'tempered_mp5', name: 'Tempered MP5', shortname: 'smg.mp5', rarity: 'mythical', price: 277000.00 },

  // --- ПИСТОЛЕТИ ---
  { id: 'revolver_basic', name: 'Revolver', shortname: 'pistol.revolver', rarity: 'common', price: 0.66 },
  { id: 'eoka_pistol', name: 'Eoka Pistol', shortname: 'pistol.eoka', rarity: 'common', price: 0.76 },
  { id: 'semi_auto_pistol', name: 'Semi-Auto Pistol', shortname: 'pistol.semiauto', rarity: 'common', price: 1.43 },
  { id: 'heat_seeker_revolver', name: 'Heat Seeker Revolver', shortname: 'pistol.revolver', rarity: 'common', price: 17.01 },
  { id: 'faded_sap', name: 'Faded SAP', shortname: 'pistol.semiauto', rarity: 'common', price: 21.38 },
  { id: 'blackout_python', name: 'Blackout Python', shortname: 'pistol.python', rarity: 'common', price: 22.71 },
  { id: 'dark_silver_python', name: 'Dark Silver Python', shortname: 'pistol.python', rarity: 'rare', price: 44.00 },
  { id: 'hot_tempered_revolver', name: 'Hot-Tempered Revolver', shortname: 'pistol.revolver', rarity: 'legendary', price: 6500.00 },
  { id: 'direct_threat_sap', name: 'Direct Threat SAP', shortname: 'pistol.semiauto', rarity: 'mythical', price: 92000.00 },

  // --- ДРОБОВИКИ ---
  { id: 'waterpipe_shotgun', name: 'Waterpipe Shotgun', shortname: 'shotgun.waterpipe', rarity: 'common', price: 1.14 },
  { id: 'polymer_pump_shotgun', name: 'Polymer Pump Shotgun', shortname: 'shotgun.pump', rarity: 'legendary', price: 3200.00 },
  { id: 'heat_double_shotgun', name: 'Heat Double Shotgun', shortname: 'shotgun.double', rarity: 'legendary', price: 4900.00 },

  // --- ВИНТОВКИ ---
  { id: 'hazard_semi_auto_rifle', name: 'Hazard Semi Auto Rifle', shortname: 'rifle.semiauto', rarity: 'common', price: 7.70 },
  { id: 'urban_light_sar', name: 'Urban Light SAR', shortname: 'rifle.semiauto', rarity: 'common', price: 12.45 },
  { id: 'metalhead_m39', name: 'Metalhead M39', shortname: 'rifle.m39', rarity: 'common', price: 13.40 },
  { id: 'survivor_lr300', name: 'Survivor LR-300', shortname: 'rifle.lr300', rarity: 'common', price: 23.47 },
  { id: 'phantom_lr300', name: 'Phantom LR-300', shortname: 'rifle.lr300', rarity: 'common', price: 5.80 },
  { id: 'imp_sar', name: 'IMP SAR', shortname: 'rifle.semiauto', rarity: 'rare', price: 746.00 },
  { id: 'comics_sar', name: 'Comics SAR', shortname: 'rifle.semiauto', rarity: 'rare', price: 1672.00 },
  { id: 'army_bolt_rifle', name: 'Army Bolt Rifle', shortname: 'rifle.bolt', rarity: 'legendary', price: 2400.00 },
  { id: 'glory_sar', name: 'Glory SAR', shortname: 'rifle.semiauto', rarity: 'legendary', price: 2600.00 },

  // --- ПУЛЕМЕТИ ---
  { id: 'black_gold_m249', name: 'Black Gold M249', shortname: 'lmg.m249', rarity: 'common', price: 6.08 },
  { id: 'bombshell_m249', name: 'Bombshell M249', shortname: 'lmg.m249', rarity: 'common', price: 32.59 },

  // --- ЛУКИ ---
  { id: 'bow_basic', name: 'Hunting Bow', shortname: 'bow.hunting', rarity: 'common', price: 0.38 },
  { id: 'crossbow_basic', name: 'Crossbow', shortname: 'crossbow', rarity: 'common', price: 0.57 },
  { id: 'compound_bow', name: 'Compound Bow', shortname: 'bow.compound', rarity: 'common', price: 0.95 },
  { id: 'blackout_bow', name: 'Blackout Bow', shortname: 'bow.hunting', rarity: 'rare', price: 38.00 },
  { id: 'legacy_bow', name: 'Legacy Bow', shortname: 'bow.hunting', rarity: 'rare', price: 130.00 },

  // --- БЛИЖНИЙ БІЙ ---
  { id: 'bone_knife', name: 'Bone Knife', shortname: 'knife.bone', rarity: 'common', price: 0.19 },
  { id: 'wooden_spear', name: 'Wooden Spear', shortname: 'spear.wooden', rarity: 'common', price: 0.24 },
  { id: 'stone_spear', name: 'Stone Spear', shortname: 'spear.stone', rarity: 'common', price: 0.48 },
  { id: 'stone_hatchet_basic', name: 'Stone Hatchet', shortname: 'stonehatchet', rarity: 'common', price: 0.29 },
  { id: 'tea_ceremony_knife', name: 'Tea Ceremony Knife', shortname: 'knife.bone', rarity: 'common', price: 9.98 },
  { id: 'aztec_jade_hachet', name: 'Aztec Jade Hachet', shortname: 'hatchet', rarity: 'common', price: 12.64 },
  { id: 'lavapick', name: 'Lavapick', shortname: 'pickaxe', rarity: 'common', price: 15.30 },
  { id: 'easter_chick_hammer', name: 'Easter Chick Hammer', shortname: 'hammer', rarity: 'common', price: 17.20 },
  { id: 'uprising_stone_pickaxe', name: 'Uprising Stone Pickaxe', shortname: 'pickaxe', rarity: 'common', price: 18.72 },
  { id: 'volcanic_stone_hatchet', name: 'Volcanic Stone Hatchet', shortname: 'hatchet', rarity: 'common', price: 24.61 },
  { id: 'danger_fork', name: 'Danger Fork', shortname: 'fork', rarity: 'common', price: 20.43 },
  { id: 'silver_leaf_hammer', name: 'Silver Leaf Hammer', shortname: 'hammer', rarity: 'rare', price: 156.00 },
  { id: 'scorched_hammer', name: 'Scorched Hammer', shortname: 'hammer', rarity: 'legendary', price: 5200.00 },
  { id: 'dragon_glass_stone_hatchet', name: 'Dragon Glass Stone Hatchet', shortname: 'hatchet', rarity: 'legendary', price: 8000.00 },
  { id: 'hot_tempered_longsword', name: 'Hot-Tempered Longsword', shortname: 'knife.combat', rarity: 'mythical', price: 211000.00 },

  // --- БРОНЯ / ОДЯГ ---
  { id: 'full_metal_helmet', name: 'Full Metal Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 2.66 },
  { id: 'tiger_mask', name: 'Tiger Mask', shortname: 'metal.facemask', rarity: 'common', price: 2.85 },
  { id: 'black_diamond_gloves', name: 'Black Diamond Gloves', shortname: 'gloves', rarity: 'common', price: 3.42 },
  { id: 'skull_bandana', name: 'Skull Bandana', shortname: 'mask.bandana', rarity: 'common', price: 3.71 },
  { id: 'flashbacks_pants', name: 'Flashbacks Pants', shortname: 'pants', rarity: 'common', price: 4.66 },
  { id: 'rust_goalkeeper_shorts', name: 'Rust Goalkeeper Shorts', shortname: 'pants.shorts', rarity: 'common', price: 5.23 },
  { id: 'road_romeo_helmet', name: 'Road Romeo Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 5.51 },
  { id: 'wasteland_hunter_boots', name: 'Wasteland Hunter Boots', shortname: 'shoes.boots', rarity: 'common', price: 7.13 },
  { id: 'nordic_beast_kilt', name: 'Nordic Beast Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 7.32 },
  { id: 'flashbacks_helmet', name: 'Flashbacks Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 7.51 },
  { id: 'wasteland_hunter_pants', name: 'Wasteland Hunter Pants', shortname: 'pants', rarity: 'common', price: 7.89 },
  { id: 'knights_templar_chestplate', name: 'Knights Templar Chestplate', shortname: 'metal.plate.torso', rarity: 'common', price: 8.08 },
  { id: 'heavenly_legion_kilt', name: 'Heavenly Legion Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 8.27 },
  { id: 'dragon_rage_hoodie', name: 'Dragon Rage Hoodie', shortname: 'hoodie', rarity: 'common', price: 8.46 },
  { id: 'black_diamond_pants', name: 'Black Diamond Pants', shortname: 'pants', rarity: 'common', price: 9.60 },
  { id: 'abyss_boots', name: 'Abyss Boots', shortname: 'shoes.boots', rarity: 'common', price: 10.36 },
  { id: 'military_chestplate', name: 'Military Chestplate', shortname: 'metal.plate.torso', rarity: 'common', price: 10.55 },
  { id: 'sand_rhino_facemask', name: 'Sand Rhino Facemask', shortname: 'metal.facemask', rarity: 'common', price: 10.74 },
  { id: 'thundergold_facemask', name: 'Thundergold Facemask', shortname: 'metal.facemask', rarity: 'common', price: 11.31 },
  { id: 'elite_forest_camo_pants', name: 'Elite Forest Camo Pants', shortname: 'pants', rarity: 'common', price: 11.50 },
  { id: 'wasteland_hunter_hoodie', name: 'Wasteland Hunter Hoodie', shortname: 'hoodie', rarity: 'common', price: 11.69 },
  { id: 'tactical_leather_gloves', name: 'Tactical Leather Gloves', shortname: 'gloves', rarity: 'common', price: 13.59 },
  { id: 'carbon_facemask', name: 'Carbon Facemask', shortname: 'metal.facemask', rarity: 'common', price: 14.35 },
  { id: 'cardboard_helmet', name: 'Cardboard Helmet', shortname: 'bucket.helmet', rarity: 'common', price: 15.49 },
  { id: 'glory_gloves', name: 'Glory Gloves', shortname: 'gloves', rarity: 'common', price: 15.68 },
  { id: 'yellow_police_jacket', name: 'Yellow Police Jacket', shortname: 'jacket', rarity: 'common', price: 16.06 },
  { id: 'flower_hat', name: 'Flower Hat', shortname: 'hat', rarity: 'common', price: 16.25 },
  { id: 'no_mercy_helmet', name: 'No Mercy Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 16.44 },
  { id: 'mummy_wraps', name: 'Mummy Wraps', shortname: 'burlap.gloves', rarity: 'common', price: 16.82 },
  { id: 'rusty_bucket_helmet', name: 'Rusty Bucket Helmet', shortname: 'bucket.helmet', rarity: 'common', price: 17.58 },
  { id: 'bee_cosplay_chestplate', name: 'Bee Cosplay Chestplate', shortname: 'metal.plate.torso', rarity: 'common', price: 17.96 },
  { id: 'reptile_hunter_vest', name: 'Reptile Hunter Vest', shortname: 'metal.plate.torso', rarity: 'common', price: 18.15 },
  { id: 'training_gloves', name: 'Training Gloves', shortname: 'gloves', rarity: 'common', price: 18.34 },
  { id: 'blackout_facemask', name: 'Blackout Facemask', shortname: 'metal.facemask', rarity: 'common', price: 18.91 },
  { id: 'black_gold_kilt', name: 'Black Gold Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 19.10 },
  { id: 'fish_shoes', name: 'Fish Shoes', shortname: 'shoes.boots', rarity: 'common', price: 19.29 },
  { id: 'homemade_shorts', name: 'Homemade Shorts', shortname: 'pants.shorts', rarity: 'common', price: 19.86 },
  { id: 'farmer_straw_hat', name: 'Farmer Straw Hat', shortname: 'hat', rarity: 'common', price: 20.05 },
  { id: 'bee_cosplay_facemask', name: 'Bee Cosplay Facemask', shortname: 'metal.facemask', rarity: 'common', price: 20.24 },
  { id: 'military_facemask', name: 'Military Facemask', shortname: 'metal.facemask', rarity: 'common', price: 20.81 },
  { id: 'desert_conqueror_hoodie', name: 'Desert Conqueror Hoodie', shortname: 'hoodie', rarity: 'common', price: 21.00 },
  { id: 'cowboy_sheriff_hat', name: 'Cowboy Sheriff Hat', shortname: 'hat', rarity: 'common', price: 21.19 },
  { id: 'predator_hoodie', name: 'Predator Hoodie', shortname: 'hoodie', rarity: 'common', price: 21.76 },
  { id: 'salvaged_plating_armor', name: 'Salvaged Plating Armor', shortname: 'metal.plate.torso', rarity: 'common', price: 21.95 },
  { id: 'urban_ice_hoodie', name: 'Urban Ice Hoodie', shortname: 'hoodie', rarity: 'common', price: 22.33 },
  { id: 'whiteout_chestplate', name: 'Whiteout Chestplate', shortname: 'metal.plate.torso', rarity: 'common', price: 22.90 },
  { id: 'cow_moo_flage_gloves', name: 'Cow Moo Flage Gloves', shortname: 'gloves', rarity: 'common', price: 23.09 },
  { id: 'glory_mask', name: 'Glory Mask', shortname: 'metal.facemask', rarity: 'common', price: 23.28 },
  { id: 'cardboard_kilt', name: 'Cardboard Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 23.85 },
  { id: 'sleazy_rider', name: 'Sleazy Rider', shortname: 'hoodie', rarity: 'common', price: 24.04 },
  { id: 'fisherman_burlap_shirt', name: 'Fisherman Burlap Shirt', shortname: 'burlap.shirt', rarity: 'common', price: 24.80 },
  { id: 'knights_templar_hoodie', name: 'Knights Templar Hoodie', shortname: 'hoodie', rarity: 'common', price: 25.18 },
  { id: 'cobalt_coffee', name: 'Cobalt Coffee', shortname: 'coffeecan.helmet', rarity: 'common', price: 25.37 },
  { id: 'uprising_hide_shoes', name: 'Uprising Hide Shoes', shortname: 'attire.hide.boots', rarity: 'common', price: 26.32 },
  { id: 'whiteout_roadsign_gloves', name: 'Whiteout Roadsign Gloves', shortname: 'roadsign.gloves', rarity: 'common', price: 27.08 },
  { id: 'phantom_hoodie', name: 'Phantom Hoodie', shortname: 'hoodie', rarity: 'common', price: 27.27 },
  { id: 'training_kilt', name: 'Training Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 27.46 },
  { id: 'thundergold_roadsign_kilt', name: 'Thundergold Roadsign Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 27.84 },
  { id: 'arctic_protection_burlap_pants', name: 'Arctic Protection Burlap Pants', shortname: 'burlap.pants', rarity: 'common', price: 28.03 },
  { id: 'reptile_hunter_chestplate', name: 'Reptile Hunter Chestplate', shortname: 'metal.plate.torso', rarity: 'common', price: 28.60 },
  { id: 'boxers_bandages', name: "Boxer's Bandages", shortname: 'gloves', rarity: 'common', price: 28.98 },
  { id: 'kayak_helmet', name: 'Kayak Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 29.17 },
  { id: 'forest_raiders_boots', name: 'Forest Raiders Boots', shortname: 'shoes.boots', rarity: 'common', price: 29.36 },
  { id: 'blue_tarp_skirt', name: 'Blue Tarp Skirt', shortname: 'roadsign.kilt', rarity: 'common', price: 29.55 },
  { id: 'knights_templar_facemask', name: 'Knights Templar Facemask', shortname: 'metal.facemask', rarity: 'common', price: 29.74 },
  { id: 'whiteout_pants', name: 'Whiteout Pants', shortname: 'pants', rarity: 'common', price: 29.93 },
  { id: 'redemption_kilt', name: 'Redemption Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 30.12 },
  { id: 'operator_helmet', name: 'Operator Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 30.50 },
  { id: 'thundergold_helmet', name: 'Thundergold Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 31.07 },
  { id: 'burlap_bandit_shirt', name: 'Burlap Bandit Shirt', shortname: 'burlap.shirt', rarity: 'common', price: 31.45 },
  { id: 'desert_patrol_pants', name: 'Desert Patrol Pants', shortname: 'pants', rarity: 'common', price: 32.02 },
  { id: 'army_armored_helmet', name: 'Army Armored Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 32.21 },
  { id: 'military_helmet', name: 'Military Helmet', shortname: 'coffeecan.helmet', rarity: 'common', price: 32.40 },
  { id: 'jpeg_roadsign_gloves', name: 'JPEG Roadsign Gloves', shortname: 'roadsign.gloves', rarity: 'common', price: 32.78 },
  { id: 'blackout_jacket', name: 'Blackout Jacket', shortname: 'jacket', rarity: 'common', price: 32.97 },
  { id: 'tribesman_hide_shirt', name: 'Tribesman Hide Shirt', shortname: 'attire.hide.helterneck', rarity: 'common', price: 33.16 },
  { id: 'burglar_mask', name: 'Burglar Mask', shortname: 'mask.bandana', rarity: 'common', price: 33.35 },
  { id: 'army_facemask', name: 'Army Facemask', shortname: 'metal.facemask', rarity: 'common', price: 33.73 },
  { id: 'training_hoodie', name: 'Training Hoodie', shortname: 'hoodie', rarity: 'common', price: 34.11 },

  // --- РЕДКІ ---
  { id: 'desert_patrol_helmet', name: 'Desert Patrol Helmet', shortname: 'coffeecan.helmet', rarity: 'rare', price: 35.00 },
  { id: 'no_mercy_gloves', name: 'No Mercy Gloves', shortname: 'gloves', rarity: 'rare', price: 37.00 },
  { id: 'farmer_overalls_bottom', name: 'Farmer Overalls Bottom', shortname: 'pants', rarity: 'rare', price: 39.00 },
  { id: 'stinger_icepick', name: 'Stinger Icepick', shortname: 'icepick', rarity: 'rare', price: 40.00 },
  { id: 'predator_pants', name: 'Predator Pants', shortname: 'pants', rarity: 'rare', price: 41.00 },
  { id: 'grey_wolf_hide_poncho', name: 'Grey Wolf Hide Poncho', shortname: 'attire.hide.poncho', rarity: 'rare', price: 43.00 },
  { id: 'knight_templar_kilt', name: 'Knight Templar Kilt', shortname: 'roadsign.kilt', rarity: 'rare', price: 46.00 },
  { id: 'military_roadsign_gloves', name: 'Military Roadsign Gloves', shortname: 'roadsign.gloves', rarity: 'rare', price: 48.00 },
  { id: 'addicted_guitarist', name: 'Addicted Guitarist', shortname: 'guitar', rarity: 'rare', price: 54.00 },
  { id: 'comics_hoodie', name: 'Comics Hoodie', shortname: 'hoodie', rarity: 'rare', price: 58.00 },
  { id: 'black_acoustic_guitar', name: 'Black Acoustic Guitar', shortname: 'guitar', rarity: 'rare', price: 82.00 },
  { id: 'elite_forest_camo_hoodie', name: 'Elite Forest Camo Hoodie', shortname: 'hoodie', rarity: 'rare', price: 86.00 },
  { id: 'fisherman_burlap_pants', name: 'Fisherman Burlap Pants', shortname: 'burlap.pants', rarity: 'rare', price: 102.00 },
  { id: 'scavenger_facemask', name: 'Scavenger Facemask', shortname: 'metal.facemask', rarity: 'rare', price: 108.00 },
  { id: 'digger_helmet', name: 'Digger Helmet', shortname: 'coffeecan.helmet', rarity: 'rare', price: 115.00 },
  { id: 'training_pants', name: 'Training Pants', shortname: 'pants', rarity: 'rare', price: 122.00 },
  { id: 'savage_facemask', name: 'Savage Facemask', shortname: 'metal.facemask', rarity: 'rare', price: 138.00 },
  { id: 'high_quality_bag', name: 'High Quality Bag', shortname: 'sleepingbag', rarity: 'rare', price: 176.00 },
  { id: 'snow_warrior_hoodie', name: 'Snow Warrior Hoodie', shortname: 'hoodie', rarity: 'rare', price: 211.00 },
  { id: 'reptile_hunter_facemask', name: 'Reptile Hunter Facemask', shortname: 'metal.facemask', rarity: 'rare', price: 224.00 },
  { id: 'uprising_hide_poncho', name: 'Uprising Hide Poncho', shortname: 'attire.hide.poncho', rarity: 'rare', price: 253.00 },
  { id: 'blackout_boots', name: 'Blackout Boots', shortname: 'shoes.boots', rarity: 'rare', price: 269.00 },
  { id: 'aztec_long_t_shirt', name: 'Aztec Long T-Shirt', shortname: 'tshirt.long', rarity: 'rare', price: 304.00 },
  { id: 'military_vest', name: 'Military Vest', shortname: 'metal.plate.torso', rarity: 'rare', price: 323.00 },
  { id: 'no_mercy_facemask', name: 'No Mercy Facemask', shortname: 'metal.facemask', rarity: 'rare', price: 343.00 },
  { id: 'desert_patrol_vest', name: 'Desert Patrol Vest', shortname: 'metal.plate.torso', rarity: 'rare', price: 365.00 },
  { id: 'cowboy_sheriff_pants', name: 'Cowboy Sheriff Pants', shortname: 'pants', rarity: 'rare', price: 438.00 },
  { id: 'rabbit_mask', name: 'Rabbit Mask', shortname: 'metal.facemask', rarity: 'rare', price: 524.00 },
  { id: 'arctic_protection_burlap_shirt', name: 'Arctic Protection Burlap Shirt', shortname: 'burlap.shirt', rarity: 'rare', price: 556.00 },
  { id: 'blackout_gloves', name: 'Blackout Gloves', shortname: 'gloves', rarity: 'rare', price: 590.00 },
  { id: 'aztek_night_hunter', name: 'Aztek Night Hunter', shortname: 'metal.facemask', rarity: 'rare', price: 626.00 },
  { id: 'blackout_helmet', name: 'Blackout Helmet', shortname: 'coffeecan.helmet', rarity: 'rare', price: 704.00 },
  { id: 'native_american_hide_shoes', name: 'Native American Hide Shoes', shortname: 'attire.hide.boots', rarity: 'rare', price: 791.00 },
  { id: 'blackout_kilt', name: 'Blackout Kilt', shortname: 'roadsign.kilt', rarity: 'rare', price: 888.00 },
  { id: 'arctic_protection_burlap_headwrap', name: 'Arctic Protection Burlap Headwrap', shortname: 'burlap.headwrap', rarity: 'rare', price: 941.00 },
  { id: 'skeleton_hoodie', name: 'Skeleton Hoodie', shortname: 'hoodie', rarity: 'rare', price: 997.00 },
  { id: 'furious_raider_riot_helmet', name: 'Furious Raider Riot Helmet', shortname: 'riot.helmet', rarity: 'rare', price: 1329.00 },
  { id: 'worker_pants', name: 'Worker Pants', shortname: 'pants', rarity: 'rare', price: 1408.00 },
  { id: 'cowboy_sheriff_hoodie', name: 'Cowboy Sheriff Hoodie', shortname: 'hoodie', rarity: 'rare', price: 1579.00 },
  { id: 'whiteout_hoodie', name: 'Whiteout Hoodie', shortname: 'hoodie', rarity: 'rare', price: 1770.00 },
  { id: 'forest_raiders_metal_chest_plate', name: 'Forest Raiders Metal Chest Plate', shortname: 'metal.plate.torso', rarity: 'rare', price: 1875.00 },
  { id: 'spacesuit', name: 'Spacesuit', shortname: 'hazmatsuit.spacesuit', rarity: 'rare', price: 1985.00 },
  { id: 'tribesman_hide_pants', name: 'Tribesman Hide Pants', shortname: 'attire.hide.pants', rarity: 'rare', price: 2100.00 },

  // --- ЛЕГЕНДАРНІ ---
  { id: 'forest_raiders_hoodie', name: 'Forest Raiders Hoodie', shortname: 'hoodie', rarity: 'legendary', price: 2200.00 },
  { id: 'rox_black_vending_machine', name: 'Rox Black Vending Machine', shortname: 'vending.machine', rarity: 'legendary', price: 2500.00 },
  { id: 'scientific_fuel_storage', name: 'Scientific Fuel Storage', shortname: 'box.wooden.large', rarity: 'legendary', price: 2800.00 },
  { id: 'whiteout_facemask', name: 'Whiteout Facemask', shortname: 'metal.facemask', rarity: 'legendary', price: 2900.00 },
  { id: 'desert_raiders_roadsign_pants', name: 'Desert Raiders Roadsign Pants', shortname: 'roadsign.kilt', rarity: 'legendary', price: 3000.00 },
  { id: 'whiteout_kilt', name: 'Whiteout Kilt', shortname: 'roadsign.kilt', rarity: 'legendary', price: 3400.00 },
  { id: 'whiteout_vest', name: 'Whiteout Vest', shortname: 'metal.plate.torso', rarity: 'legendary', price: 3600.00 },
  { id: 'no_mercy_hoodie', name: 'No Mercy Hoodie', shortname: 'hoodie', rarity: 'legendary', price: 3800.00 },
  { id: 'blackout_vest', name: 'Blackout Vest', shortname: 'metal.plate.torso', rarity: 'legendary', price: 4000.00 },
  { id: 'forest_raiders_facemask', name: 'Forest Raiders Facemask', shortname: 'metal.facemask', rarity: 'legendary', price: 4300.00 },
  { id: 'wasteland_hunter_gloves', name: 'Wasteland Hunter Gloves', shortname: 'gloves', rarity: 'legendary', price: 4600.00 },
  { id: 'rat_mask', name: 'Rat Mask', shortname: 'metal.facemask', rarity: 'legendary', price: 5600.00 },
  { id: 'military_kilt', name: 'Military Kilt', shortname: 'roadsign.kilt', rarity: 'legendary', price: 6000.00 },
  { id: 'skull_door_knocker', name: 'Skull Door Knocker', shortname: 'door.hinged.metal', rarity: 'legendary', price: 7000.00 },
  { id: 'blackout_hoodie', name: 'Blackout Hoodie', shortname: 'hoodie', rarity: 'legendary', price: 7500.00 },
  { id: 'press_vest', name: 'Press Vest', shortname: 'metal.plate.torso', rarity: 'legendary', price: 8600.00 },
  { id: 'desert_raiders_helmet', name: 'Desert Raiders Helmet', shortname: 'coffeecan.helmet', rarity: 'legendary', price: 9200.00 },
  { id: 'desert_raiders_hoodie', name: 'Desert Raiders Hoodie', shortname: 'hoodie', rarity: 'legendary', price: 10000.00 },
  { id: 'panda_rug', name: 'Panda Rug', shortname: 'rug', rarity: 'legendary', price: 10800.00 },
  { id: 'blackout_pants', name: 'Blackout Pants', shortname: 'pants', rarity: 'legendary', price: 11600.00 },
  { id: 'military_camo_roadsign_kilt', name: 'Military Camo Roadsign Kilt', shortname: 'roadsign.kilt', rarity: 'legendary', price: 12500.00 },
  { id: 'desert_raiders_roadsign_vest', name: 'Desert Raiders Roadsign Vest', shortname: 'roadsign.jacket', rarity: 'legendary', price: 13500.00 },
  { id: 'no_mercy_pants', name: 'No Mercy Pants', shortname: 'pants', rarity: 'legendary', price: 16800.00 },
  { id: 'soviet_carpet', name: 'Soviet Carpet', shortname: 'rug', rarity: 'legendary', price: 18000.00 },
  { id: 'checkpoint_riot_helmet', name: 'Checkpoint Riot Helmet', shortname: 'riot.helmet', rarity: 'legendary', price: 19400.00 },
  { id: 'desert_raiders_pants', name: 'Desert Raiders Pants', shortname: 'pants', rarity: 'legendary', price: 24300.00 },
  { id: 'no_mercy_jacket', name: 'No Mercy Jacket', shortname: 'jacket', rarity: 'legendary', price: 26200.00 },
  { id: 'cow_moo_flage_pants', name: 'Cow Moo Flage Pants', shortname: 'pants', rarity: 'legendary', price: 30400.00 },
  { id: 'whiteout_helmet', name: 'Whiteout Helmet', shortname: 'coffeecan.helmet', rarity: 'legendary', price: 32800.00 },
  { id: 'forest_raiders_pants', name: 'Forest Raiders Pants', shortname: 'pants', rarity: 'legendary', price: 35400.00 },
  { id: 'forest_raiders_roadsign_gloves', name: 'Forest Raiders Roadsign Gloves', shortname: 'roadsign.gloves', rarity: 'legendary', price: 44400.00 },
  { id: 'surgeon_scrubs', name: 'Surgeon Scrubs', shortname: 'hazmatsuit', rarity: 'legendary', price: 51500.00 },
  { id: 'forest_raiders_helmet', name: 'Forest Raiders Helmet', shortname: 'coffeecan.helmet', rarity: 'legendary', price: 59600.00 },
  { id: 'space_rocket_work_gloves', name: 'Space Rocket Work Gloves', shortname: 'gloves', rarity: 'legendary', price: 68900.00 },
  { id: 'forest_raiders_roadsign_vest', name: 'Forest Raiders Roadsign Vest', shortname: 'roadsign.jacket', rarity: 'legendary', price: 79500.00 },
  { id: 'desert_raiders_chest_plate', name: 'Desert Raiders Chest Plate', shortname: 'metal.plate.torso', rarity: 'legendary', price: 85400.00 },

  // --- МІФІЧНІ ---
  { id: 'tea_vending_machine', name: 'Tea Vending Machine', shortname: 'vending.machine', rarity: 'mythical', price: 99000.00 },
  { id: 'desert_raiders_facemask', name: 'Desert Raiders Facemask', shortname: 'metal.facemask', rarity: 'mythical', price: 106000.00 },
  { id: 'forest_raiders_roadsign_pants', name: 'Forest Raiders Roadsign Pants', shortname: 'roadsign.kilt', rarity: 'mythical', price: 122000.00 },
  { id: 'plate_carrier_black', name: 'Plate Carrier - Black', shortname: 'metal.plate.torso', rarity: 'mythical', price: 131000.00 },
  { id: 'legendary_gold_facemask', name: 'Legendary Gold Facemask', shortname: 'metal.facemask', rarity: 'mythical', price: 140000.00 },
  { id: 'stainless_facemask', name: 'Stainless Facemask', shortname: 'metal.facemask', rarity: 'mythical', price: 150000.00 },
  { id: 'gold_rock', name: 'Gold Rock', shortname: 'rock', rarity: 'mythical', price: 161000.00 },
  { id: 'christmas_lights', name: 'Christmas Lights', shortname: 'xmas.lights', rarity: 'mythical', price: 184000.00 },
  { id: 'glowing_skull', name: 'Glowing Skull', shortname: 'metal.facemask', rarity: 'mythical', price: 197000.00 },
  { id: 'tempered_mask', name: 'Tempered Mask', shortname: 'metal.facemask', rarity: 'mythical', price: 226000.00 },
  { id: 'neon_dragon_garage_door', name: 'Neon Dragon Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'mythical', price: 297000.00 },
  { id: 'creepy_clown_bandana', name: 'Creepy Clown Bandana', shortname: 'mask.bandana', rarity: 'mythical', price: 318000.00 },
  { id: 'big_grin', name: 'Big Grin', shortname: 'metal.facemask', rarity: 'mythical', price: 340000.00 },
  { id: 'horror_bag', name: 'Horror Bag', shortname: 'sleepingbag', rarity: 'mythical', price: 364000.00 },

  // --- ДВЕРІ / СТРОЙКИ ---
  { id: 'dungeon_garage_door', name: 'Dungeon Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'common', price: 4.09 },
  { id: 'twisted_metal_double_door', name: 'Twisted Metal Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 4.37 },
  { id: 'ancient_totem_furnace', name: 'Ancient Totem Furnace', shortname: 'furnace', rarity: 'common', price: 6.37 },
  { id: 'bandit_rug', name: 'Bandit Rug', shortname: 'rug', rarity: 'common', price: 6.65 },
  { id: 'furnace_from_hell', name: 'Furnace From Hell', shortname: 'furnace', rarity: 'common', price: 9.22 },
  { id: 'greening_area_garage_door', name: 'Greening Area Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'common', price: 9.41 },
  { id: 'reptile_hunter_large_backpack', name: 'Reptile Hunter Large Backpack', shortname: 'backpack', rarity: 'common', price: 9.79 },
  { id: 'neon_pumpkin_metal_double_door', name: 'Neon Pumpkin Metal Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 10.17 },
  { id: 'cobalt_container_metal_door', name: 'Cobalt Container Metal Door', shortname: 'door.hinged.metal', rarity: 'common', price: 10.93 },
  { id: 'neon_charcoal_storage', name: 'Neon Charcoal Storage', shortname: 'box.wooden.large', rarity: 'common', price: 11.88 },
  { id: 'comics_sleeping_bag', name: 'Comics Sleeping Bag', shortname: 'sleepingbag', rarity: 'common', price: 12.07 },
  { id: 'abyss_sleeping_bag', name: 'Abyss Sleeping Bag', shortname: 'sleepingbag', rarity: 'common', price: 12.26 },
  { id: 'no_mercy_kilt', name: 'No Mercy Kilt', shortname: 'roadsign.kilt', rarity: 'common', price: 13.02 },
  { id: 'neon_frags_storage', name: 'Neon Frags Storage', shortname: 'box.wooden.large', rarity: 'common', price: 13.21 },
  { id: 'no_mercy_garage_door', name: 'No Mercy Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'common', price: 13.78 },
  { id: 'uap_pilot_sleeping_bag', name: 'UAP Pilot Sleeping Bag', shortname: 'sleepingbag', rarity: 'common', price: 13.97 },
  { id: 'pirate_bed', name: 'Pirate Bed', shortname: 'bed', rarity: 'common', price: 14.16 },
  { id: 'polished_obsidian_furnace', name: 'Polished Obsidian Furnace', shortname: 'furnace', rarity: 'common', price: 14.73 },
  { id: 'spooky_speaker', name: 'Spooky Speaker', shortname: 'speaker', rarity: 'common', price: 14.92 },
  { id: 'bombshell_garage_door', name: 'Bombshell Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'common', price: 15.87 },
  { id: 'bombshell_sheet_metal_door', name: 'Bombshell Sheet Metal Door', shortname: 'door.hinged.metal', rarity: 'common', price: 16.63 },
  { id: 'pirate_sheet_metal_door', name: 'Pirate Sheet Metal Door', shortname: 'door.hinged.metal', rarity: 'common', price: 17.77 },
  { id: 'neon_bismuth_armored_double_door', name: 'Neon Bismuth Armored Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 18.53 },
  { id: 'fireflies_metal_door', name: 'Fireflies Metal Door', shortname: 'door.hinged.metal', rarity: 'common', price: 19.48 },
  { id: 'ancient_gods_furnace', name: 'Ancient Gods Furnace', shortname: 'furnace', rarity: 'common', price: 19.67 },
  { id: 'scientific_gunpowder_storage', name: 'Scientific Gunpowder Storage', shortname: 'box.wooden.large', rarity: 'common', price: 20.62 },
  { id: 'urban_vending_machine', name: 'Urban Vending Machine', shortname: 'vending.machine', rarity: 'common', price: 21.57 },
  { id: 'grass_rug', name: 'Grass Rug', shortname: 'rug', rarity: 'common', price: 23.66 },
  { id: 'going_deep_garage_door', name: 'Going Deep Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'common', price: 24.23 },
  { id: 'space_station_armored_double_door', name: 'Space Station Armored Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 24.42 },
  { id: 'forest_camo_bag', name: 'Forest Camo Bag', shortname: 'sleepingbag', rarity: 'common', price: 25.56 },
  { id: 'forest_camouflage_net', name: 'Forest Camouflage Net', shortname: 'net', rarity: 'common', price: 25.94 },
  { id: 'jack_sheet_metal_double_door', name: 'Jack Sheet Metal Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 26.51 },
  { id: 'cargo_heli_locker', name: 'Cargo Heli Locker', shortname: 'locker', rarity: 'common', price: 26.70 },
  { id: 'weapon_barrel', name: 'Weapon Barrel', shortname: 'box.wooden.large', rarity: 'common', price: 26.89 },
  { id: 'popstar_garage_door', name: 'Popstar Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'common', price: 28.22 },
  { id: 'crypt_armored_double_door', name: 'Crypt Armored Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 28.41 },
  { id: 'urban_night_door', name: 'Urban Night Door', shortname: 'door.hinged.metal', rarity: 'common', price: 28.79 },
  { id: 'scientific_guns_storage', name: 'Scientific Guns Storage', shortname: 'box.wooden.large', rarity: 'common', price: 30.31 },
  { id: 'abyss_metal_double_door', name: 'Abyss Metal Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 30.69 },
  { id: 'neon_bismuth_metal_double_door', name: 'Neon Bismuth Metal Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 30.88 },
  { id: 'brutalist_garage_door', name: 'Brutalist Garage Door', shortname: 'wall.frame.garagedoor', rarity: 'common', price: 31.64 },
  { id: 'beauty_industry_double_door', name: 'Beauty Industry Double Door', shortname: 'door.double.hinged.metal', rarity: 'common', price: 31.83 },
  { id: 'tools_supply_container', name: 'Tools Supply Container', shortname: 'box.wooden.large', rarity: 'common', price: 33.54 },
  { id: 'cargo_heli_storage', name: 'Cargo Heli Storage', shortname: 'box.wooden.large', rarity: 'common', price: 33.92 }
];
